#include "../journal_internal.h"
#include "../journal_reader.c" /* Live storage fixture uses internal snapshot; SYSTEM gate stays production-only. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned checks,failures;
#define CHECK(x) do{++checks;if(!(x)){++failures;printf("FAIL reader %u: %s (error %lu)\n",__LINE__,#x,GetLastError());}}while(0)
static bool count(DWORD kind,ULONGLONG seq,const void* bytes,DWORD size,void* context){(void)kind;(void)bytes;(void)size;unsigned* n=context;CHECK(seq==++*n);return true;}
static bool bytes(const wchar_t* path,const BYTE* data,DWORD size){HANDLE h=CreateFileW(path,GENERIC_WRITE,0,NULL,OPEN_EXISTING,0,NULL);if(h==INVALID_HANDLE_VALUE)return false;DWORD n;bool ok=WriteFile(h,data,size,&n,NULL)&&n==size&&SetEndOfFile(h)&&FlushFileBuffers(h);CloseHandle(h);return ok;}
static void cleanup(const wchar_t* root){wchar_t pattern[MAX_PATH],child[MAX_PATH];swprintf_s(pattern,MAX_PATH,L"%ls\\*",root);WIN32_FIND_DATAW d;HANDLE h=FindFirstFileW(pattern,&d);if(h!=INVALID_HANDLE_VALUE){do{if(!wcscmp(d.cFileName,L".")||!wcscmp(d.cFileName,L".."))continue;swprintf_s(child,MAX_PATH,L"%ls\\%ls",root,d.cFileName);if(d.dwFileAttributes&FILE_ATTRIBUTE_DIRECTORY){if(!(d.dwFileAttributes&FILE_ATTRIBUTE_REPARSE_POINT))cleanup(child);else RemoveDirectoryW(child);}else DeleteFileW(child);}while(FindNextFileW(h,&d));FindClose(h);}RemoveDirectoryW(root);}
int wmain(void){wchar_t temp[MAX_PATH],root[MAX_PATH],pf[MAX_PATH],pd[MAX_PATH],oldfile[MAX_PATH],alias[MAX_PATH];CHECK(GetTempPathW(MAX_PATH,temp));swprintf_s(root,MAX_PATH,L"%lsl4reader-%lu-%llu",temp,GetCurrentProcessId(),GetTickCount64());if(!CreateDirectoryW(root,NULL))return 1;swprintf_s(pf,MAX_PATH,L"%ls\\PF",root);swprintf_s(pd,MAX_PATH,L"%ls\\PD",root);L4Layout layout;CHECK(l4_layout_from_roots(&layout,pf,pd,L"1.13.8"));CHECK(l4_layout_prepare(&layout));
 const wchar_t* source=L"17730000-0000-4000-8000-0000000000ab";const wchar_t* current=L"17730000-0000-4000-8000-0000000000cd";L4Journal *old=NULL,*owner=NULL;CHECK(l4_journal_open(&layout,source,true,&old));if(!old){cleanup(root);return 1;}ULONGLONG seq;CHECK(l4_journal_append(old,123,"receipt",7,&seq));CHECK(seq==1);CHECK(l4_journal_append(old,124,"more",4,NULL));swprintf_s(oldfile,MAX_PATH,L"%ls\\journal.bin",old->directory);l4_journal_close(old);
 BYTE original[1024];DWORD original_size=0;HANDLE input=CreateFileW(oldfile,GENERIC_READ,FILE_SHARE_READ,NULL,OPEN_EXISTING,0,NULL);CHECK(input!=INVALID_HANDLE_VALUE);if(input!=INVALID_HANDLE_VALUE){CHECK(ReadFile(input,original,sizeof(original)-1,&original_size,NULL));CloseHandle(input);}
 CHECK(l4_journal_open(&layout,current,true,&owner));if(!owner){cleanup(root);return 1;}L4JournalReader* reader=NULL;
 CHECK(!l4_journal_reader_open(owner,current,&reader));CHECK(!l4_journal_reader_open(owner,L"17730000-0000-4000-8000-0000000000AB",&reader));CHECK(!l4_journal_reader_open(owner,L"17730000-0000-4000-8000-000000000000",&reader));
 CHECK(l4_journal_reader_open(owner,source,&reader));if(reader){CHECK(l4_journal_reader_is_immutable(reader));unsigned records=0;CHECK(l4_journal_reader_replay(reader,count,&records));CHECK(records==2);BYTE* b=NULL;DWORD n=0;CHECK(l4_journal_reader_find(reader,123,1,&b,&n));CHECK(n==7&&!memcmp(b,"receipt",7));free(b);CHECK(!l4_journal_reader_find(reader,123,2,&b,&n));
 HANDLE writer=CreateFileW(oldfile,GENERIC_WRITE,FILE_SHARE_READ,NULL,OPEN_EXISTING,0,NULL);CHECK(writer==INVALID_HANDLE_VALUE&&GetLastError()==ERROR_SHARING_VIOLATION);if(writer!=INVALID_HANDLE_VALUE)CloseHandle(writer);CHECK(!DeleteFileW(oldfile));l4_journal_reader_close(reader);reader=NULL;}
 original[original_size]=0x7f;CHECK(bytes(oldfile,original,original_size+1));CHECK(!l4_journal_reader_open(owner,source,&reader));LARGE_INTEGER actual;input=CreateFileW(oldfile,GENERIC_READ,FILE_SHARE_READ,NULL,OPEN_EXISTING,0,NULL);CHECK(input!=INVALID_HANDLE_VALUE);if(input!=INVALID_HANDLE_VALUE){CHECK(GetFileSizeEx(input,&actual)&&actual.QuadPart==original_size+1);CloseHandle(input);}CHECK(bytes(oldfile,original,original_size));
 BYTE saved=original[24+16];original[24+16]^=1;CHECK(bytes(oldfile,original,original_size));CHECK(!l4_journal_reader_open(owner,source,&reader));original[24+16]=saved;CHECK(bytes(oldfile,original,original_size));
 saved=original[8];original[8]^=1;CHECK(bytes(oldfile,original,original_size));CHECK(!l4_journal_reader_open(owner,source,&reader));original[8]=saved;CHECK(bytes(oldfile,original,original_size));
 CHECK(!l4_journal_reader_open_live(&layout,current,&reader)&&GetLastError()==ERROR_ACCESS_DENIED);
 GUID live_id;CHECK(uuid(current,&live_id));CHECK(snapshot(&layout,current,&live_id,INVALID_HANDLE_VALUE,true,&reader));
 if(reader){CHECK(l4_journal_reader_codec_view(reader)==NULL);CHECK(l4_journal_append(owner,100,"ok",2,NULL));unsigned records=0;CHECK(l4_journal_reader_replay(reader,count,&records)&&records==0);l4_journal_reader_close(reader);reader=NULL;}
 wchar_t livefile[MAX_PATH];swprintf_s(livefile,MAX_PATH,L"%ls\\journal.bin",owner->directory);LARGE_INTEGER tail;tail.QuadPart=(LONGLONG)owner->end;DWORD written=0;BYTE pending=0x7f;CHECK(SetFilePointerEx(owner->file,tail,NULL,FILE_BEGIN)&&WriteFile(owner->file,&pending,1,&written,NULL)&&written==1&&FlushFileBuffers(owner->file));
 CHECK(!snapshot(&layout,current,&live_id,INVALID_HANDLE_VALUE,true,&reader)&&GetLastError()==ERROR_IO_PENDING&&reader==NULL);
 CHECK(SetFilePointerEx(owner->file,tail,NULL,FILE_BEGIN)&&SetEndOfFile(owner->file)&&FlushFileBuffers(owner->file));CHECK(snapshot(&layout,current,&live_id,INVALID_HANDLE_VALUE,true,&reader));if(reader){CHECK(!l4_journal_reader_is_immutable(reader));unsigned records=0;CHECK(l4_journal_reader_replay(reader,count,&records)&&records==1);l4_journal_reader_close(reader);reader=NULL;}
 swprintf_s(alias,MAX_PATH,L"%ls\\alias.bin",root);CHECK(CreateHardLinkW(alias,oldfile,NULL));CHECK(!l4_journal_reader_open(owner,source,&reader));CHECK(DeleteFileW(alias));CHECK(l4_journal_reader_open(owner,source,&reader));l4_journal_reader_close(reader);l4_journal_close(owner);cleanup(root);CHECK(GetFileAttributesW(root)==INVALID_FILE_ATTRIBUTES);
 printf("strict journal reader: %u checks, %u failures\n",checks,failures);return failures?1:0;}
