/* Isolated real SCM rights regression: owns one unique STOPPED service, never
 * starts it and never opens a suite service. Run elevated or primary SYSTEM. */
#include "../supervisor_crash_profile.h"
#include <stdio.h>
static unsigned checks,failures;
#define CHECK(x) do{checks++;if(!(x)){failures++;printf("FAIL crash rights %u error%lu: %s\n",__LINE__,GetLastError(),#x);}}while(0)
static bool elevated_primary(void){HANDLE thread=NULL,token=NULL;DWORD needed=0;TOKEN_TYPE type=TokenImpersonation;TOKEN_ELEVATION elevation={0};if(OpenThreadToken(GetCurrentThread(),TOKEN_QUERY,TRUE,&thread)){CloseHandle(thread);return false;}if(GetLastError()!=ERROR_NO_TOKEN)return false;bool ok=OpenProcessToken(GetCurrentProcess(),TOKEN_QUERY,&token)&&GetTokenInformation(token,TokenType,&type,sizeof(type),&needed)&&type==TokenPrimary&&GetTokenInformation(token,TokenElevation,&elevation,sizeof(elevation),&needed)&&elevation.TokenIsElevated;if(token)CloseHandle(token);return ok;}
int wmain(void){if(!elevated_primary()){printf("Real SCM prerequisite unavailable: elevated primary token required; no service created\n");return 2;}wchar_t name[96],module[MAX_PATH],command[MAX_PATH+3];swprintf_s(name,96,L"L4CrashRights_%lu_%llu",GetCurrentProcessId(),GetTickCount64());CHECK(GetModuleFileNameW(NULL,module,MAX_PATH));swprintf_s(command,MAX_PATH+3,L"\"%ls\"",module);
 SC_HANDLE manager=OpenSCManagerW(NULL,NULL,SC_MANAGER_CONNECT|SC_MANAGER_CREATE_SERVICE);if(!manager){DWORD error=GetLastError();printf("Real SCM prerequisite unavailable: %lu; no service created\n",error);return error==ERROR_ACCESS_DENIED||error==ERROR_PRIVILEGE_NOT_HELD?2:1;}
 const DWORD oldrights=SERVICE_QUERY_CONFIG|SERVICE_QUERY_STATUS|DELETE|SERVICE_CHANGE_CONFIG;SC_HANDLE service=CreateServiceW(manager,name,name,oldrights,SERVICE_WIN32_OWN_PROCESS,SERVICE_DEMAND_START,SERVICE_ERROR_NORMAL,command,NULL,NULL,NULL,L"LocalSystem",NULL);CHECK(service!=NULL);if(!service){CloseServiceHandle(manager);return 1;}
 SERVICE_STATUS_PROCESS status={0};DWORD needed=0;CHECK(QueryServiceStatusEx(service,SC_STATUS_PROCESS_INFO,(BYTE*)&status,sizeof(status),&needed)&&status.dwCurrentState==SERVICE_STOPPED&&!status.dwProcessId);
 SetLastError(0);CHECK(!l4_supervisor_crash_profile_write(service)&&GetLastError()==ERROR_ACCESS_DENIED);CHECK(!l4_supervisor_crash_profile_read(service,L4_SUPERVISOR_RESTART_MS));CHECK(CloseServiceHandle(service));
 service=OpenServiceW(manager,name,oldrights|SERVICE_START);CHECK(service!=NULL);if(service){CHECK(l4_supervisor_crash_profile_write(service));CHECK(l4_supervisor_crash_profile_read(service,L4_SUPERVISOR_RESTART_MS));CHECK(QueryServiceStatusEx(service,SC_STATUS_PROCESS_INFO,(BYTE*)&status,sizeof(status),&needed)&&status.dwCurrentState==SERVICE_STOPPED&&!status.dwProcessId);CHECK(DeleteService(service));CHECK(CloseServiceHandle(service));}
 else{SC_HANDLE cleanup=OpenServiceW(manager,name,DELETE);CHECK(cleanup!=NULL);if(cleanup){CHECK(DeleteService(cleanup));CHECK(CloseServiceHandle(cleanup));}}
 ULONGLONG end=GetTickCount64()+10000;bool absent=false;do{SC_HANDLE remaining=OpenServiceW(manager,name,SERVICE_QUERY_STATUS);DWORD error=GetLastError();if(remaining)CloseServiceHandle(remaining);if(!remaining&&error==ERROR_SERVICE_DOES_NOT_EXIST){absent=true;break;}if(!remaining&&error!=ERROR_SERVICE_MARKED_FOR_DELETE)break;Sleep(20);}while(GetTickCount64()<end);CHECK(absent);CHECK(CloseServiceHandle(manager));printf("Real SCM crash rights: %u passed, %u failed; missingSTART denied, fixedrights profile readback, neverstarted, ownedservice removed\n",checks-failures,failures);return failures?1:0;}
