//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью wsdl, версия=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="SendScriptsToKioskSoap", Namespace="http://tempuri.org/")]
public partial class SendScriptsToKiosk : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback DelAllScriptsForKioskOperationCompleted;
    
    private System.Threading.SendOrPostCallback SendRawScriptToKiosksOperationCompleted;
    
    private System.Threading.SendOrPostCallback SendRawScriptToAllOrgKiosksOperationCompleted;
    
    private System.Threading.SendOrPostCallback SendScriptsOperationCompleted;
    
    private System.Threading.SendOrPostCallback UpdateTspStatusesToOrgOperationCompleted;
    
    private System.Threading.SendOrPostCallback UpdateTspStatusesToKioskOperationCompleted;
    
    private System.Threading.SendOrPostCallback SendTemplateToKioskOperationCompleted;
    
    private System.Threading.SendOrPostCallback SendTemplateToAllKiosksOperationCompleted;
    
    private System.Threading.SendOrPostCallback SendTemplateDefaultToOrgOperationCompleted;
    
    private System.Threading.SendOrPostCallback SendPropertiesToKioskOperationCompleted;
    
    private System.Threading.SendOrPostCallback SendOrgPropertiesToKiosksOperationCompleted;
    
    private System.Threading.SendOrPostCallback SendCommissionShemeOperationCompleted;
    
    private System.Threading.SendOrPostCallback SendCommissionShemesToKioskOperationCompleted;
    
    private System.Threading.SendOrPostCallback SendCommissionShemeAttachOperationCompleted;
    
    private System.Threading.SendOrPostCallback SendCommissionShemeAttachToKiosksOperationCompleted;
    
    /// <remarks/>
    public SendScriptsToKiosk(string url) {
        this.Url = url;
    }
    
    /// <remarks/>
    public event DelAllScriptsForKioskCompletedEventHandler DelAllScriptsForKioskCompleted;
    
    /// <remarks/>
    public event SendRawScriptToKiosksCompletedEventHandler SendRawScriptToKiosksCompleted;
    
    /// <remarks/>
    public event SendRawScriptToAllOrgKiosksCompletedEventHandler SendRawScriptToAllOrgKiosksCompleted;
    
    /// <remarks/>
    public event SendScriptsCompletedEventHandler SendScriptsCompleted;
    
    /// <remarks/>
    public event UpdateTspStatusesToOrgCompletedEventHandler UpdateTspStatusesToOrgCompleted;
    
    /// <remarks/>
    public event UpdateTspStatusesToKioskCompletedEventHandler UpdateTspStatusesToKioskCompleted;
    
    /// <remarks/>
    public event SendTemplateToKioskCompletedEventHandler SendTemplateToKioskCompleted;
    
    /// <remarks/>
    public event SendTemplateToAllKiosksCompletedEventHandler SendTemplateToAllKiosksCompleted;
    
    /// <remarks/>
    public event SendTemplateDefaultToOrgCompletedEventHandler SendTemplateDefaultToOrgCompleted;
    
    /// <remarks/>
    public event SendPropertiesToKioskCompletedEventHandler SendPropertiesToKioskCompleted;
    
    /// <remarks/>
    public event SendOrgPropertiesToKiosksCompletedEventHandler SendOrgPropertiesToKiosksCompleted;
    
    /// <remarks/>
    public event SendCommissionShemeCompletedEventHandler SendCommissionShemeCompleted;
    
    /// <remarks/>
    public event SendCommissionShemesToKioskCompletedEventHandler SendCommissionShemesToKioskCompleted;
    
    /// <remarks/>
    public event SendCommissionShemeAttachCompletedEventHandler SendCommissionShemeAttachCompleted;
    
    /// <remarks/>
    public event SendCommissionShemeAttachToKiosksCompletedEventHandler SendCommissionShemeAttachToKiosksCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DelAllScriptsForKiosk", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void DelAllScriptsForKiosk(int kioskNumber) {
        this.Invoke("DelAllScriptsForKiosk", new object[] {
                    kioskNumber});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDelAllScriptsForKiosk(int kioskNumber, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DelAllScriptsForKiosk", new object[] {
                    kioskNumber}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndDelAllScriptsForKiosk(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void DelAllScriptsForKioskAsync(int kioskNumber) {
        this.DelAllScriptsForKioskAsync(kioskNumber, null);
    }
    
    /// <remarks/>
    public void DelAllScriptsForKioskAsync(int kioskNumber, object userState) {
        if ((this.DelAllScriptsForKioskOperationCompleted == null)) {
            this.DelAllScriptsForKioskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelAllScriptsForKioskOperationCompleted);
        }
        this.InvokeAsync("DelAllScriptsForKiosk", new object[] {
                    kioskNumber}, this.DelAllScriptsForKioskOperationCompleted, userState);
    }
    
    private void OnDelAllScriptsForKioskOperationCompleted(object arg) {
        if ((this.DelAllScriptsForKioskCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DelAllScriptsForKioskCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendRawScriptToKiosks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SendRawScriptToKiosks(string script, string kioskList, int userId) {
        this.Invoke("SendRawScriptToKiosks", new object[] {
                    script,
                    kioskList,
                    userId});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSendRawScriptToKiosks(string script, string kioskList, int userId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SendRawScriptToKiosks", new object[] {
                    script,
                    kioskList,
                    userId}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSendRawScriptToKiosks(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SendRawScriptToKiosksAsync(string script, string kioskList, int userId) {
        this.SendRawScriptToKiosksAsync(script, kioskList, userId, null);
    }
    
    /// <remarks/>
    public void SendRawScriptToKiosksAsync(string script, string kioskList, int userId, object userState) {
        if ((this.SendRawScriptToKiosksOperationCompleted == null)) {
            this.SendRawScriptToKiosksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendRawScriptToKiosksOperationCompleted);
        }
        this.InvokeAsync("SendRawScriptToKiosks", new object[] {
                    script,
                    kioskList,
                    userId}, this.SendRawScriptToKiosksOperationCompleted, userState);
    }
    
    private void OnSendRawScriptToKiosksOperationCompleted(object arg) {
        if ((this.SendRawScriptToKiosksCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendRawScriptToKiosksCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendRawScriptToAllOrgKiosks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SendRawScriptToAllOrgKiosks(string script, int orgId, int userId) {
        this.Invoke("SendRawScriptToAllOrgKiosks", new object[] {
                    script,
                    orgId,
                    userId});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSendRawScriptToAllOrgKiosks(string script, int orgId, int userId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SendRawScriptToAllOrgKiosks", new object[] {
                    script,
                    orgId,
                    userId}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSendRawScriptToAllOrgKiosks(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SendRawScriptToAllOrgKiosksAsync(string script, int orgId, int userId) {
        this.SendRawScriptToAllOrgKiosksAsync(script, orgId, userId, null);
    }
    
    /// <remarks/>
    public void SendRawScriptToAllOrgKiosksAsync(string script, int orgId, int userId, object userState) {
        if ((this.SendRawScriptToAllOrgKiosksOperationCompleted == null)) {
            this.SendRawScriptToAllOrgKiosksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendRawScriptToAllOrgKiosksOperationCompleted);
        }
        this.InvokeAsync("SendRawScriptToAllOrgKiosks", new object[] {
                    script,
                    orgId,
                    userId}, this.SendRawScriptToAllOrgKiosksOperationCompleted, userState);
    }
    
    private void OnSendRawScriptToAllOrgKiosksOperationCompleted(object arg) {
        if ((this.SendRawScriptToAllOrgKiosksCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendRawScriptToAllOrgKiosksCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendScripts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SendScripts(int kioskNumber) {
        this.Invoke("SendScripts", new object[] {
                    kioskNumber});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSendScripts(int kioskNumber, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SendScripts", new object[] {
                    kioskNumber}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSendScripts(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SendScriptsAsync(int kioskNumber) {
        this.SendScriptsAsync(kioskNumber, null);
    }
    
    /// <remarks/>
    public void SendScriptsAsync(int kioskNumber, object userState) {
        if ((this.SendScriptsOperationCompleted == null)) {
            this.SendScriptsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendScriptsOperationCompleted);
        }
        this.InvokeAsync("SendScripts", new object[] {
                    kioskNumber}, this.SendScriptsOperationCompleted, userState);
    }
    
    private void OnSendScriptsOperationCompleted(object arg) {
        if ((this.SendScriptsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendScriptsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateTspStatusesToOrg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void UpdateTspStatusesToOrg(int orgId, int tspId, int status) {
        this.Invoke("UpdateTspStatusesToOrg", new object[] {
                    orgId,
                    tspId,
                    status});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdateTspStatusesToOrg(int orgId, int tspId, int status, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UpdateTspStatusesToOrg", new object[] {
                    orgId,
                    tspId,
                    status}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndUpdateTspStatusesToOrg(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void UpdateTspStatusesToOrgAsync(int orgId, int tspId, int status) {
        this.UpdateTspStatusesToOrgAsync(orgId, tspId, status, null);
    }
    
    /// <remarks/>
    public void UpdateTspStatusesToOrgAsync(int orgId, int tspId, int status, object userState) {
        if ((this.UpdateTspStatusesToOrgOperationCompleted == null)) {
            this.UpdateTspStatusesToOrgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTspStatusesToOrgOperationCompleted);
        }
        this.InvokeAsync("UpdateTspStatusesToOrg", new object[] {
                    orgId,
                    tspId,
                    status}, this.UpdateTspStatusesToOrgOperationCompleted, userState);
    }
    
    private void OnUpdateTspStatusesToOrgOperationCompleted(object arg) {
        if ((this.UpdateTspStatusesToOrgCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateTspStatusesToOrgCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateTspStatusesToKiosk", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void UpdateTspStatusesToKiosk(int kioskNumber) {
        this.Invoke("UpdateTspStatusesToKiosk", new object[] {
                    kioskNumber});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdateTspStatusesToKiosk(int kioskNumber, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UpdateTspStatusesToKiosk", new object[] {
                    kioskNumber}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndUpdateTspStatusesToKiosk(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void UpdateTspStatusesToKioskAsync(int kioskNumber) {
        this.UpdateTspStatusesToKioskAsync(kioskNumber, null);
    }
    
    /// <remarks/>
    public void UpdateTspStatusesToKioskAsync(int kioskNumber, object userState) {
        if ((this.UpdateTspStatusesToKioskOperationCompleted == null)) {
            this.UpdateTspStatusesToKioskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTspStatusesToKioskOperationCompleted);
        }
        this.InvokeAsync("UpdateTspStatusesToKiosk", new object[] {
                    kioskNumber}, this.UpdateTspStatusesToKioskOperationCompleted, userState);
    }
    
    private void OnUpdateTspStatusesToKioskOperationCompleted(object arg) {
        if ((this.UpdateTspStatusesToKioskCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateTspStatusesToKioskCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendTemplateToKiosk", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SendTemplateToKiosk(int kioskNumber) {
        this.Invoke("SendTemplateToKiosk", new object[] {
                    kioskNumber});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSendTemplateToKiosk(int kioskNumber, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SendTemplateToKiosk", new object[] {
                    kioskNumber}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSendTemplateToKiosk(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SendTemplateToKioskAsync(int kioskNumber) {
        this.SendTemplateToKioskAsync(kioskNumber, null);
    }
    
    /// <remarks/>
    public void SendTemplateToKioskAsync(int kioskNumber, object userState) {
        if ((this.SendTemplateToKioskOperationCompleted == null)) {
            this.SendTemplateToKioskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendTemplateToKioskOperationCompleted);
        }
        this.InvokeAsync("SendTemplateToKiosk", new object[] {
                    kioskNumber}, this.SendTemplateToKioskOperationCompleted, userState);
    }
    
    private void OnSendTemplateToKioskOperationCompleted(object arg) {
        if ((this.SendTemplateToKioskCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendTemplateToKioskCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendTemplateToAllKiosks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SendTemplateToAllKiosks(int templateId) {
        this.Invoke("SendTemplateToAllKiosks", new object[] {
                    templateId});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSendTemplateToAllKiosks(int templateId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SendTemplateToAllKiosks", new object[] {
                    templateId}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSendTemplateToAllKiosks(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SendTemplateToAllKiosksAsync(int templateId) {
        this.SendTemplateToAllKiosksAsync(templateId, null);
    }
    
    /// <remarks/>
    public void SendTemplateToAllKiosksAsync(int templateId, object userState) {
        if ((this.SendTemplateToAllKiosksOperationCompleted == null)) {
            this.SendTemplateToAllKiosksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendTemplateToAllKiosksOperationCompleted);
        }
        this.InvokeAsync("SendTemplateToAllKiosks", new object[] {
                    templateId}, this.SendTemplateToAllKiosksOperationCompleted, userState);
    }
    
    private void OnSendTemplateToAllKiosksOperationCompleted(object arg) {
        if ((this.SendTemplateToAllKiosksCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendTemplateToAllKiosksCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendTemplateDefaultToOrg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SendTemplateDefaultToOrg(int orgId) {
        this.Invoke("SendTemplateDefaultToOrg", new object[] {
                    orgId});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSendTemplateDefaultToOrg(int orgId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SendTemplateDefaultToOrg", new object[] {
                    orgId}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSendTemplateDefaultToOrg(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SendTemplateDefaultToOrgAsync(int orgId) {
        this.SendTemplateDefaultToOrgAsync(orgId, null);
    }
    
    /// <remarks/>
    public void SendTemplateDefaultToOrgAsync(int orgId, object userState) {
        if ((this.SendTemplateDefaultToOrgOperationCompleted == null)) {
            this.SendTemplateDefaultToOrgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendTemplateDefaultToOrgOperationCompleted);
        }
        this.InvokeAsync("SendTemplateDefaultToOrg", new object[] {
                    orgId}, this.SendTemplateDefaultToOrgOperationCompleted, userState);
    }
    
    private void OnSendTemplateDefaultToOrgOperationCompleted(object arg) {
        if ((this.SendTemplateDefaultToOrgCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendTemplateDefaultToOrgCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendPropertiesToKiosk", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SendPropertiesToKiosk(int kioskNumber) {
        this.Invoke("SendPropertiesToKiosk", new object[] {
                    kioskNumber});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSendPropertiesToKiosk(int kioskNumber, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SendPropertiesToKiosk", new object[] {
                    kioskNumber}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSendPropertiesToKiosk(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SendPropertiesToKioskAsync(int kioskNumber) {
        this.SendPropertiesToKioskAsync(kioskNumber, null);
    }
    
    /// <remarks/>
    public void SendPropertiesToKioskAsync(int kioskNumber, object userState) {
        if ((this.SendPropertiesToKioskOperationCompleted == null)) {
            this.SendPropertiesToKioskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendPropertiesToKioskOperationCompleted);
        }
        this.InvokeAsync("SendPropertiesToKiosk", new object[] {
                    kioskNumber}, this.SendPropertiesToKioskOperationCompleted, userState);
    }
    
    private void OnSendPropertiesToKioskOperationCompleted(object arg) {
        if ((this.SendPropertiesToKioskCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendPropertiesToKioskCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendOrgPropertiesToKiosks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SendOrgPropertiesToKiosks(int orgId) {
        this.Invoke("SendOrgPropertiesToKiosks", new object[] {
                    orgId});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSendOrgPropertiesToKiosks(int orgId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SendOrgPropertiesToKiosks", new object[] {
                    orgId}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSendOrgPropertiesToKiosks(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SendOrgPropertiesToKiosksAsync(int orgId) {
        this.SendOrgPropertiesToKiosksAsync(orgId, null);
    }
    
    /// <remarks/>
    public void SendOrgPropertiesToKiosksAsync(int orgId, object userState) {
        if ((this.SendOrgPropertiesToKiosksOperationCompleted == null)) {
            this.SendOrgPropertiesToKiosksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendOrgPropertiesToKiosksOperationCompleted);
        }
        this.InvokeAsync("SendOrgPropertiesToKiosks", new object[] {
                    orgId}, this.SendOrgPropertiesToKiosksOperationCompleted, userState);
    }
    
    private void OnSendOrgPropertiesToKiosksOperationCompleted(object arg) {
        if ((this.SendOrgPropertiesToKiosksCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendOrgPropertiesToKiosksCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendCommissionSheme", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SendCommissionSheme(int commissionId) {
        this.Invoke("SendCommissionSheme", new object[] {
                    commissionId});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSendCommissionSheme(int commissionId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SendCommissionSheme", new object[] {
                    commissionId}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSendCommissionSheme(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SendCommissionShemeAsync(int commissionId) {
        this.SendCommissionShemeAsync(commissionId, null);
    }
    
    /// <remarks/>
    public void SendCommissionShemeAsync(int commissionId, object userState) {
        if ((this.SendCommissionShemeOperationCompleted == null)) {
            this.SendCommissionShemeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendCommissionShemeOperationCompleted);
        }
        this.InvokeAsync("SendCommissionSheme", new object[] {
                    commissionId}, this.SendCommissionShemeOperationCompleted, userState);
    }
    
    private void OnSendCommissionShemeOperationCompleted(object arg) {
        if ((this.SendCommissionShemeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendCommissionShemeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendCommissionShemesToKiosk", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SendCommissionShemesToKiosk(int kioskNumber) {
        this.Invoke("SendCommissionShemesToKiosk", new object[] {
                    kioskNumber});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSendCommissionShemesToKiosk(int kioskNumber, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SendCommissionShemesToKiosk", new object[] {
                    kioskNumber}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSendCommissionShemesToKiosk(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SendCommissionShemesToKioskAsync(int kioskNumber) {
        this.SendCommissionShemesToKioskAsync(kioskNumber, null);
    }
    
    /// <remarks/>
    public void SendCommissionShemesToKioskAsync(int kioskNumber, object userState) {
        if ((this.SendCommissionShemesToKioskOperationCompleted == null)) {
            this.SendCommissionShemesToKioskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendCommissionShemesToKioskOperationCompleted);
        }
        this.InvokeAsync("SendCommissionShemesToKiosk", new object[] {
                    kioskNumber}, this.SendCommissionShemesToKioskOperationCompleted, userState);
    }
    
    private void OnSendCommissionShemesToKioskOperationCompleted(object arg) {
        if ((this.SendCommissionShemesToKioskCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendCommissionShemesToKioskCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendCommissionShemeAttach", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SendCommissionShemeAttach(int kioskNumber) {
        this.Invoke("SendCommissionShemeAttach", new object[] {
                    kioskNumber});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSendCommissionShemeAttach(int kioskNumber, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SendCommissionShemeAttach", new object[] {
                    kioskNumber}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSendCommissionShemeAttach(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SendCommissionShemeAttachAsync(int kioskNumber) {
        this.SendCommissionShemeAttachAsync(kioskNumber, null);
    }
    
    /// <remarks/>
    public void SendCommissionShemeAttachAsync(int kioskNumber, object userState) {
        if ((this.SendCommissionShemeAttachOperationCompleted == null)) {
            this.SendCommissionShemeAttachOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendCommissionShemeAttachOperationCompleted);
        }
        this.InvokeAsync("SendCommissionShemeAttach", new object[] {
                    kioskNumber}, this.SendCommissionShemeAttachOperationCompleted, userState);
    }
    
    private void OnSendCommissionShemeAttachOperationCompleted(object arg) {
        if ((this.SendCommissionShemeAttachCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendCommissionShemeAttachCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendCommissionShemeAttachToKiosks", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SendCommissionShemeAttachToKiosks(string kioskNumbers) {
        this.Invoke("SendCommissionShemeAttachToKiosks", new object[] {
                    kioskNumbers});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSendCommissionShemeAttachToKiosks(string kioskNumbers, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SendCommissionShemeAttachToKiosks", new object[] {
                    kioskNumbers}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSendCommissionShemeAttachToKiosks(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void SendCommissionShemeAttachToKiosksAsync(string kioskNumbers) {
        this.SendCommissionShemeAttachToKiosksAsync(kioskNumbers, null);
    }
    
    /// <remarks/>
    public void SendCommissionShemeAttachToKiosksAsync(string kioskNumbers, object userState) {
        if ((this.SendCommissionShemeAttachToKiosksOperationCompleted == null)) {
            this.SendCommissionShemeAttachToKiosksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendCommissionShemeAttachToKiosksOperationCompleted);
        }
        this.InvokeAsync("SendCommissionShemeAttachToKiosks", new object[] {
                    kioskNumbers}, this.SendCommissionShemeAttachToKiosksOperationCompleted, userState);
    }
    
    private void OnSendCommissionShemeAttachToKiosksOperationCompleted(object arg) {
        if ((this.SendCommissionShemeAttachToKiosksCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendCommissionShemeAttachToKiosksCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void DelAllScriptsForKioskCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void SendRawScriptToKiosksCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void SendRawScriptToAllOrgKiosksCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void SendScriptsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void UpdateTspStatusesToOrgCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void UpdateTspStatusesToKioskCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void SendTemplateToKioskCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void SendTemplateToAllKiosksCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void SendTemplateDefaultToOrgCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void SendPropertiesToKioskCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void SendOrgPropertiesToKiosksCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void SendCommissionShemeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void SendCommissionShemesToKioskCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void SendCommissionShemeAttachCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void SendCommissionShemeAttachToKiosksCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
