//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18052
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sotex
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "urn:payicoinservice98", ConfigurationName = "Sotex.payicoinservice98PortType")]
    public interface payicoinservice98PortType
    {

        [System.ServiceModel.OperationContractAttribute(Action = "urn:payicoinservice98#request98", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        Sotex.Responds request98(Sotex.Paysdata paysdata);

        [System.ServiceModel.OperationContractAttribute(Action = "urn:payicoinservice98#request02", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        Sotex.Responds request02(Sotex.Paysdata paysdata);

        [System.ServiceModel.OperationContractAttribute(Action = "urn:payicoinservice98#request22", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        Sotex.Responds request22(Sotex.Paysdata paysdata);

        [System.ServiceModel.OperationContractAttribute(Action = "urn:payicoinservice98#Responds", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        Sotex.Responds sendstatus(Sotex.Statusdata statusdata);

        [System.ServiceModel.OperationContractAttribute(Action = "urn:payicoinservice98#request25", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        Sotex.Responds references(Sotex.Paysdata paysdatatry);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "urn:payicoinservice98")]
    public partial class Paysdata : object, System.ComponentModel.INotifyPropertyChanged
    {


        private string numtermField;

        private string numberField;

        private string opertypeField;

        private float sumField;

        private float sumwbField;

        private string notesField;

        private string idpayField;

        private string idterminalField;

        private string signatureField;

        /// <remarks/>
        public string numterm
        {
            get
            {
                return this.numtermField;
            }
            set
            {
                this.numtermField = value;
                this.RaisePropertyChanged("numterm");
            }
        }

        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }

        /// <remarks/>
        public string opertype
        {
            get
            {
                return this.opertypeField;
            }
            set
            {
                this.opertypeField = value;
                this.RaisePropertyChanged("opertype");
            }
        }

        /// <remarks/>
        public float sum
        {
            get
            {
                return this.sumField;
            }
            set
            {
                this.sumField = value;
                this.RaisePropertyChanged("sum");
            }
        }

        /// <remarks/>
        public float sumwb
        {
            get
            {
                return this.sumwbField;
            }
            set
            {
                this.sumwbField = value;
                this.RaisePropertyChanged("sumwb");
            }
        }

        /// <remarks/>
        public string notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
                this.RaisePropertyChanged("notes");
            }
        }

        /// <remarks/>
        public string idpay
        {
            get
            {
                return this.idpayField;
            }
            set
            {
                this.idpayField = value;
                this.RaisePropertyChanged("idpay");
            }
        }

        /// <remarks/>
        public string idterminal
        {
            get
            {
                return this.idterminalField;
            }
            set
            {
                this.idterminalField = value;
                this.RaisePropertyChanged("idterminal");
            }
        }

        /// <remarks/>
        public string signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
                this.RaisePropertyChanged("signature");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "urn:payicoinservice98")]
    public partial class Statusdata : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string idterminalField;

        private int statusField;

        private float totalmField;

        private int totalbField;

        private int paperprintedField;

        private string notesField;

        /// <remarks/>
        public string idterminal
        {
            get
            {
                return this.idterminalField;
            }
            set
            {
                this.idterminalField = value;
                this.RaisePropertyChanged("idterminal");
            }
        }

        /// <remarks/>
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }

        /// <remarks/>
        public float totalm
        {
            get
            {
                return this.totalmField;
            }
            set
            {
                this.totalmField = value;
                this.RaisePropertyChanged("totalm");
            }
        }

        /// <remarks/>
        public int totalb
        {
            get
            {
                return this.totalbField;
            }
            set
            {
                this.totalbField = value;
                this.RaisePropertyChanged("totalb");
            }
        }

        /// <remarks/>
        public int paperprinted
        {
            get
            {
                return this.paperprintedField;
            }
            set
            {
                this.paperprintedField = value;
                this.RaisePropertyChanged("paperprinted");
            }
        }

        /// <remarks/>
        public string notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
                this.RaisePropertyChanged("notes");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "urn:payicoinservice98")]
    public partial class Responds : object, System.ComponentModel.INotifyPropertyChanged
    {

        private int errorpayField;

        private string messagepayField;

        private string makeField;

        private string signatureField;

        /// <remarks/>
        public int errorpay
        {
            get
            {
                return this.errorpayField;
            }
            set
            {
                this.errorpayField = value;
                this.RaisePropertyChanged("errorpay");
            }
        }

        /// <remarks/>
        public string messagepay
        {
            get
            {
                return this.messagepayField;
            }
            set
            {
                this.messagepayField = value;
                this.RaisePropertyChanged("messagepay");
            }
        }

        /// <remarks/>
        public string make
        {
            get
            {
                return this.makeField;
            }
            set
            {
                this.makeField = value;
                this.RaisePropertyChanged("make");
            }
        }

        /// <remarks/>
        public string signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
                this.RaisePropertyChanged("signature");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface payicoinservice98PortTypeChannel : Sotex.payicoinservice98PortType, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class payicoinservice98PortTypeClient : System.ServiceModel.ClientBase<Sotex.payicoinservice98PortType>, Sotex.payicoinservice98PortType
    {

        public payicoinservice98PortTypeClient()
        {
        }

        public payicoinservice98PortTypeClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public payicoinservice98PortTypeClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public payicoinservice98PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public payicoinservice98PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public Sotex.Responds request98(Sotex.Paysdata paysdata)
        {
            return base.Channel.request98(paysdata);
        }

        public Sotex.Responds request02(Sotex.Paysdata paysdata)
        {
            return base.Channel.request02(paysdata);
        }

        public Sotex.Responds request22(Sotex.Paysdata paysdata)
        {
            return base.Channel.request22(paysdata);
        }

        public Sotex.Responds sendstatus(Sotex.Statusdata statusdata)
        {
            return base.Channel.sendstatus(statusdata);
        }

        public Sotex.Responds references(Sotex.Paysdata paysdatatry)
        {
            return base.Channel.references(paysdatatry);
        }
    }
}
