#include "acceptance_local.h"
#include "acceptance_entry.h"
#include "../../l4common/journal_internal.h"
#include "../../l4common/remote_host.h"
#include "../../l4common/physical_console_token.h"
#include "uac.h"
#include "../../leo4proxy/src/policy_json.h"
#include <sddl.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#define INTENT_SIZE 320u
struct SetupAcceptancePin {L4Journal* owner;const L4JournalReader* reader;L4Layout layout;wchar_t directory[MAX_PATH];L4FileFence ancestry,fence;HANDLE files[5];BYTE intent[INTENT_SIZE],*catalog,*signature,*authorization,*authorization_signature;DWORD catalog_size,signature_size,authorization_size,authorization_signature_size;L4Catalog* parsed;SetupAcceptanceFacts facts;bool bound;};
static bool fail(DWORD e){SetLastError(e);return false;}
static ULONGLONG utc(void){FILETIME t;GetSystemTimeAsFileTime(&t);return ((ULONGLONG)t.dwHighDateTime<<32)|t.dwLowDateTime;}
static bool primary_system(void){HANDLE thread=NULL,token=NULL;BYTE user[sizeof(TOKEN_USER)+SECURITY_MAX_SID_SIZE];DWORD n=0,session=~0u;TOKEN_TYPE type=TokenImpersonation;
 if(OpenThreadToken(GetCurrentThread(),TOKEN_QUERY,TRUE,&thread)){CloseHandle(thread);return fail(ERROR_ACCESS_DENIED);}if(GetLastError()!=ERROR_NO_TOKEN)return false;
 bool ok=OpenProcessToken(GetCurrentProcess(),TOKEN_QUERY,&token)&&GetTokenInformation(token,TokenUser,user,sizeof(user),&n)&&IsWellKnownSid(((TOKEN_USER*)user)->User.Sid,WinLocalSystemSid)&&GetTokenInformation(token,TokenType,&type,sizeof(type),&n)&&type==TokenPrimary&&GetTokenInformation(token,TokenSessionId,&session,sizeof(session),&n)&&!session;if(token)CloseHandle(token);return ok?true:fail(ERROR_ACCESS_DENIED);
}
static bool original(L4Journal* j){if(!j||!j->lock||j->lock==INVALID_HANDLE_VALUE||j->poisoned)return fail(ERROR_INVALID_STATE);const wchar_t* v=wcsrchr(j->layout.release,L'\\');L4Layout native;return v&&l4_layout_resolve(&native,v+1)&&!memcmp(&native,&j->layout,sizeof(native))?true:fail(ERROR_BAD_PATHNAME);}
static bool text(const BYTE* bytes,unsigned size){const BYTE* end=memchr(bytes,0,size);if(!end||end==bytes)return false;for(const BYTE* p=end;p<bytes+size;p++)if(*p)return false;return true;}
static bool authorization(SetupAcceptancePin* p,bool stage){
 if(!l4_metadata_verify_trusted(p->authorization,p->authorization_size,p->authorization_signature,p->authorization_signature_size,p->facts.authorization_sha256))return false;
 PolicyJson json;unsigned long long schema=0,expires=0,terminal=0,tenant=0;char kind[64],operation[40],source[32],target[32],arch[8],hash[65];bool force=false;
 if(!policy_json_parse(&json,(const char*)p->authorization,p->authorization_size)||json.count!=23||
 !policy_json_uint(&json,policy_json_field(&json,0,"schema"),&schema)||schema!=1||!policy_json_string(&json,policy_json_field(&json,0,"kind"),kind,sizeof(kind))||strcmp(kind,"l4tools-local-acceptance")||
 !policy_json_string(&json,policy_json_field(&json,0,"operation_id"),operation,sizeof(operation))||strcmp(operation,(const char*)p->intent+108)||
 !policy_json_string(&json,policy_json_field(&json,0,"source_version"),source,sizeof(source))||strcmp(source,(const char*)p->intent+145)||
 !policy_json_string(&json,policy_json_field(&json,0,"target_version"),target,sizeof(target))||strcmp(target,(const char*)p->intent+177)||
 !policy_json_string(&json,policy_json_field(&json,0,"arch"),arch,sizeof(arch))||strcmp(arch,(const char*)p->intent+209)||
 !policy_json_bool(&json,policy_json_field(&json,0,"force_rollback"),&force)||
 !policy_json_uint(&json,policy_json_field(&json,0,"terminal_id"),&terminal)||terminal!=773||!policy_json_uint(&json,policy_json_field(&json,0,"tenant_id"),&tenant)||tenant!=1||
 !policy_json_uint(&json,policy_json_field(&json,0,"expires_at"),&expires)||expires>253402300799ULL||
 !policy_json_string(&json,policy_json_field(&json,0,"catalog_sha256"),hash,sizeof(hash))||strlen(hash)!=64)return fail(ERROR_INVALID_DATA);
 static const char hex[]="0123456789abcdef";for(unsigned i=0;i<32;i++)if(hash[i*2]!=hex[p->intent[217+i]>>4]||hash[i*2+1]!=hex[p->intent[217+i]&15])return fail(ERROR_REVISION_MISMATCH);
 ULONGLONG deadline=116444736000000000ULL+expires*10000000ULL,now=utc();if(deadline<=now||(stage&&deadline-now>864000000000ULL))return fail(ERROR_TIMEOUT);
 if(stage){l4_store_u32(p->intent+12,force?1:0);if(deadline<l4_store_get64(p->intent+24))l4_store_u64(p->intent+24,deadline);}
 else if(force!=(l4_store_get32(p->intent+12)!=0)||l4_store_get64(p->intent+24)>deadline)return fail(ERROR_REVISION_MISMATCH);
 return true;
}
static bool sufficient_lifetime(ULONGLONG deadline){ULONGLONG now=utc();return deadline>now && deadline-now>=(ULONGLONG)SETUP_ACCEPTANCE_OUTER_WAIT_MS*10000ULL?true:fail(ERROR_TIMEOUT);}
static bool version(const L4Layout* roots,const char* s){wchar_t wide[32];L4Layout out;return strcmp(s,"latest")&&MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,s,-1,wide,32)&&l4_layout_from_roots(&out,roots->binaries,roots->data,wide);}
static bool uuid(const char* s){if(strlen(s)!=36)return false;bool any=false;for(unsigned i=0;i<36;i++){bool dash=i==8||i==13||i==18||i==23;if(dash?s[i]!='-':!((s[i]>='0'&&s[i]<='9')||(s[i]>='a'&&s[i]<='f')))return false;else if(!dash&&s[i]!='0')any=true;}return any;}
static bool decode(SetupAcceptancePin* p){const BYTE* b=p->intent;if(memcmp(b,"L4ACTR01",8)||l4_store_get32(b+8)!=1||l4_store_get32(b+12)>1||!text(b+108,37)||!uuid((const char*)b+108)||!text(b+145,32)||!text(b+177,32)||!text(b+209,8))return fail(ERROR_INVALID_DATA);
 DWORD n=l4_store_get32(b+36);if(n<8||n>SECURITY_MAX_SID_SIZE||!IsValidSid((PSID)(b+40))||GetLengthSid((PSID)(b+40))!=n||!l4_store_get32(b+32))return fail(ERROR_INVALID_DATA);for(unsigned i=n;i<68;i++)if(b[40+i])return fail(ERROR_INVALID_DATA);for(unsigned i=289;i<INTENT_SIZE;i++)if(b[i])return fail(ERROR_INVALID_DATA);
 SetupAcceptanceFacts* f=&p->facts;strcpy_s(f->operation,37,(const char*)b+108);strcpy_s(f->source_version,32,(const char*)b+145);strcpy_s(f->target_version,32,(const char*)b+177);strcpy_s(f->arch,8,(const char*)b+209);
 const wchar_t* id=wcsrchr(p->directory,L'\\'),*source=wcsrchr(p->layout.release,L'\\');wchar_t wide[40];if(!id||!source||!MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,f->operation,-1,wide,40)||wcscmp(id+1,wide)||!MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,f->source_version,-1,wide,40)||wcscmp(source+1,wide)||!version(&p->layout,f->target_version)||!strcmp(f->source_version,f->target_version)||(strcmp(f->arch,"x86")&&strcmp(f->arch,"x64")))return fail(ERROR_REVISION_MISMATCH);
 f->created_utc=l4_store_get64(b+16);f->expires_utc=l4_store_get64(b+24);ULONGLONG now=utc();if(!f->created_utc||f->created_utc>now||f->expires_utc<=now||f->expires_utc<=f->created_utc||f->expires_utc-f->created_utc>144000000000ULL)return fail(ERROR_TIMEOUT);f->force_rollback=l4_store_get32(b+12)!=0;f->configured_terminal=773;f->configured_tenant=1;
 return l4_store_hash(b,INTENT_SIZE,NULL,0,f->intent_sha256);
}
static bool operator_matches(const SetupAcceptancePin* p){DWORD session=0,n=0;LUID authentication={0};HANDLE token=l4_physical_console_token(&session,&authentication);if(!token)return false;BYTE user[sizeof(TOKEN_USER)+SECURITY_MAX_SID_SIZE];bool ok=session==l4_store_get32(p->intent+32)&&authentication.LowPart==l4_store_get32(p->intent+281)&&(DWORD)authentication.HighPart==l4_store_get32(p->intent+285)&&GetTokenInformation(token,TokenUser,user,sizeof(user),&n)&&EqualSid(((TOKEN_USER*)user)->User.Sid,(PSID)(p->intent+40));DWORD e=GetLastError();CloseHandle(token);return ok?true:fail(e?e:ERROR_ACCESS_DENIED);}
static bool read_file(const wchar_t* path,DWORD maximum,bool private,HANDLE* held,BYTE** bytes,DWORD* size){*held=CreateFileW(path,GENERIC_READ|READ_CONTROL,FILE_SHARE_READ,NULL,OPEN_EXISTING,FILE_FLAG_OPEN_REPARSE_POINT,NULL);if(*held==INVALID_HANDLE_VALUE)return false;
 BY_HANDLE_FILE_INFORMATION info;FILE_STREAM_INFO streams[128];LARGE_INTEGER length={0};BYTE* sd=NULL;DWORD sd_size=0;bool ok=GetFileInformationByHandle(*held,&info)&&info.nNumberOfLinks==1&&!(info.dwFileAttributes&(FILE_ATTRIBUTE_REPARSE_POINT|FILE_ATTRIBUTE_DIRECTORY))&&GetFileInformationByHandleEx(*held,FileStreamInfo,streams,sizeof(streams))&&!streams[0].NextEntryOffset&&streams[0].StreamNameLength==14&&!memcmp(streams[0].StreamName,L"::$DATA",14)&&GetFileSizeEx(*held,&length)&&length.QuadPart>0&&length.QuadPart<=maximum;
 if(ok&&private)ok=l4_store_security(*held,true,&sd,&sd_size);free(sd);if(!ok)return fail(ERROR_INVALID_DATA);*size=(DWORD)length.QuadPart;*bytes=malloc(*size);DWORD read=0;return *bytes&&ReadFile(*held,*bytes,*size,&read,NULL)&&read==*size?true:fail(ERROR_INVALID_DATA);
}
void setup_acceptance_close(SetupAcceptancePin* p){if(!p)return;DWORD e=GetLastError();for(unsigned i=0;i<5;i++)if(p->files[i]&&p->files[i]!=INVALID_HANDLE_VALUE)CloseHandle(p->files[i]);l4_store_unpin(&p->fence);l4_store_unpin(&p->ancestry);l4_catalog_free(p->parsed);free(p->catalog);free(p->signature);free(p->authorization);free(p->authorization_signature);free(p);SetLastError(e);}
const SetupAcceptanceFacts* setup_acceptance_facts(const SetupAcceptancePin* p){return p&&p->bound?&p->facts:NULL;}
static bool open_inputs(SetupAcceptancePin* p,bool optional,SetupAcceptancePin** out){DWORD error=ERROR_INVALID_DATA;BYTE* intent=NULL;DWORD n=0;wchar_t path[MAX_PATH];
 /* ProgramData ancestry permits public read; the UUID control boundary remains private. */
 if(!l4_store_pin(p->directory,p->layout.data,false,&p->ancestry)||!l4_store_pin(p->directory,p->directory,true,&p->fence))goto done;
 if(swprintf_s(path,MAX_PATH,L"%ls\\acceptance.local",p->directory)<0)goto done;
 if(!read_file(path,INTENT_SIZE,true,&p->files[0],&intent,&n)){error=GetLastError();if(optional&&error==ERROR_FILE_NOT_FOUND){const wchar_t* leaves[]={L"acceptance.catalog.json",L"acceptance.catalog.json.sig",L"acceptance.authorization.json",L"acceptance.authorization.json.sig"};for(unsigned i=0;i<4;i++){if(swprintf_s(path,MAX_PATH,L"%ls\\%ls",p->directory,leaves[i])<0)goto done;DWORD attributes=GetFileAttributesW(path);if(attributes!=INVALID_FILE_ATTRIBUTES||GetLastError()!=ERROR_FILE_NOT_FOUND){error=ERROR_INVALID_STATE;goto done;}}setup_acceptance_close(p);return true;}goto done;}if(n!=INTENT_SIZE)goto done;memcpy(p->intent,intent,INTENT_SIZE);free(intent);intent=NULL;if(!decode(p)||!operator_matches(p))goto done;
 if(swprintf_s(path,MAX_PATH,L"%ls\\acceptance.catalog.json",p->directory)<0||!read_file(path,L4_METADATA_MAX_BYTES,true,&p->files[1],&p->catalog,&p->catalog_size))goto done;
 if(swprintf_s(path,MAX_PATH,L"%ls\\acceptance.catalog.json.sig",p->directory)<0||!read_file(path,L4_METADATA_SIGNATURE_BYTES,true,&p->files[2],&p->signature,&p->signature_size))goto done;
 if(swprintf_s(path,MAX_PATH,L"%ls\\acceptance.authorization.json",p->directory)<0||!read_file(path,4096,true,&p->files[3],&p->authorization,&p->authorization_size))goto done;
 if(swprintf_s(path,MAX_PATH,L"%ls\\acceptance.authorization.json.sig",p->directory)<0||!read_file(path,L4_METADATA_SIGNATURE_BYTES,true,&p->files[4],&p->authorization_signature,&p->authorization_signature_size)||!authorization(p,false))goto done;
 BYTE hash[32];if(!l4_metadata_verify_trusted(p->catalog,p->catalog_size,p->signature,p->signature_size,p->facts.catalog_sha256)||memcmp(p->facts.catalog_sha256,p->intent+217,32)||!l4_store_hash(p->signature,p->signature_size,NULL,0,hash)||memcmp(hash,p->intent+249,32)||!l4_catalog_parse_trusted(p->catalog,p->catalog_size,p->signature,p->signature_size,(utc()-116444736000000000ULL)/10000000ULL,&p->parsed))goto done;
 if(!l4_platform_current(p->facts.profile))goto done;*out=p;return true;
done:if(error==ERROR_INVALID_DATA&&GetLastError())error=GetLastError();free(intent);setup_acceptance_close(p);return fail(error);
}
bool setup_acceptance_open_optional(L4Journal* j,SetupAcceptancePin** out){if(!out)return fail(ERROR_INVALID_PARAMETER);*out=NULL;if(!primary_system()||!original(j))return false;SetupAcceptancePin* p=calloc(1,sizeof(*p));if(!p)return fail(ERROR_NOT_ENOUGH_MEMORY);p->owner=j;p->layout=j->layout;wcscpy_s(p->directory,MAX_PATH,j->directory);return open_inputs(p,true,out);}
bool setup_acceptance_verify(SetupAcceptancePin* p,L4Journal* j){if(!p||p->owner!=j||!primary_system()||!original(j)||!operator_matches(p)||utc()>=p->facts.expires_utc||!authorization(p,false))return fail(ERROR_ACCESS_DENIED);char profile[L4_PLATFORM_PROFILE_SIZE];if(!l4_platform_current(profile)||strcmp(profile,p->facts.profile))return fail(ERROR_REVISION_MISMATCH);if(j->sequence){L4RemoteRequest request;if(!l4_remote_request_load(j,&request)||request.target!=L4_REMOTE_SUITE||strcmp(request.version,p->facts.target_version))return fail(ERROR_REVISION_MISMATCH);}return true;}
bool setup_acceptance_prelaunch(SetupAcceptancePin* p,L4Journal* j){return setup_acceptance_verify(p,j)&&sufficient_lifetime(p->facts.expires_utc);}
static bool bind_route(SetupAcceptancePin* p,const char* version_value,const BYTE hash[32],const char* arch){if(strcmp(p->facts.source_version,version_value)||strcmp(p->facts.arch,arch))return fail(ERROR_REVISION_MISMATCH);L4CatalogRoute route={0};if(!l4_catalog_route(p->parsed,version_value,hash,p->facts.target_version,arch,p->facts.profile,&route)||route.count!=1||strcmp(route.releases[0].version,p->facts.target_version))return fail(ERROR_NOT_SUPPORTED);memcpy(p->facts.source_root,hash,32);memcpy(p->facts.target_root,route.releases[0].manifest_sha256,32);p->bound=true;return true;}
bool setup_acceptance_bind(SetupAcceptancePin* p,L4Journal* j,SetupInstalledSource* source){if(!p||!source||!setup_acceptance_verify(p,j)||!setup_installed_source_owned_by(source,j)||!setup_installed_source_verify(source))return false;const BYTE* hash=setup_root_identity(setup_installed_source_root(source));return hash&&bind_route(p,setup_installed_source_suite_version(source),hash,setup_installed_source_arch(source));}
static bool plan_binding(SetupAcceptancePin* p,const SetupOperationPlan* operation){const L4RoutePlan* route=setup_operation_route(operation);L4CatalogRelease source;const SetupRootManifest* target=setup_operation_target_root(operation,0);const BYTE* target_hash=target?setup_root_identity(target):NULL;if(!route||!l4_route_is_owner_trusted(route)||setup_operation_hops(operation)!=1||!l4_route_source(route,&source)||!target_hash||strcmp(l4_route_requested(route),p->facts.target_version)||strcmp(l4_route_profile(route),p->facts.profile)||memcmp(l4_route_catalog_sha256(route),p->facts.catalog_sha256,32)||!bind_route(p,source.version,source.manifest_sha256,l4_route_arch(route))||memcmp(target_hash,p->facts.target_root,32))return fail(ERROR_REVISION_MISMATCH);p->facts.catalog_revision=l4_route_revision(route);return true;}
bool setup_acceptance_bind_plan(SetupAcceptancePin* p,L4Journal* j,const SetupOperationPlan* operation){return p&&operation&&setup_acceptance_verify(p,j)&&plan_binding(p,operation);}
typedef struct{const L4Layout* roots;const char* target;bool found;} RequestBinding;
static bool snapshot_request(DWORD kind,ULONGLONG seq,const void* bytes,DWORD size,void* context){RequestBinding* b=context;if(kind!=92)return true;L4RemoteRequest request;if(b->found||seq!=1||!l4_remote_request_decode(b->roots,bytes,size,&request)||request.target!=L4_REMOTE_SUITE||strcmp(request.version,b->target))return fail(ERROR_REVISION_MISMATCH);b->found=true;return true;}
bool setup_acceptance_verify_snapshot(SetupAcceptancePin* p,const L4JournalReader* reader,const L4Layout* roots,const SetupOperationPlan* operation){if(!p||!reader||p->reader!=reader||p->owner||!roots||memcmp(roots,&p->layout,sizeof(*roots))||!operation||!primary_system()||!l4_journal_reader_is_immutable(reader)||wcscmp(l4_journal_reader_directory(reader),p->directory)||!operator_matches(p)||utc()>=p->facts.expires_utc||!authorization(p,false))return fail(ERROR_ACCESS_DENIED);char profile[L4_PLATFORM_PROFILE_SIZE];if(!l4_platform_current(profile)||strcmp(profile,p->facts.profile))return fail(ERROR_REVISION_MISMATCH);RequestBinding request={roots,p->facts.target_version,false};return l4_journal_reader_replay(reader,snapshot_request,&request)&&request.found&&plan_binding(p,operation);}
bool setup_acceptance_open_snapshot(const L4JournalReader* reader,const L4Layout* roots,const SetupOperationPlan* operation,SetupAcceptancePin** out){if(!out)return fail(ERROR_INVALID_PARAMETER);*out=NULL;if(!reader||!roots||!operation||!primary_system()||!l4_journal_reader_is_immutable(reader))return fail(ERROR_ACCESS_DENIED);const wchar_t* v=wcsrchr(roots->release,L'\\');L4Layout native;if(!v||!l4_layout_resolve(&native,v+1)||memcmp(&native,roots,sizeof(native)))return fail(ERROR_BAD_PATHNAME);SetupAcceptancePin* p=calloc(1,sizeof(*p));if(!p)return fail(ERROR_NOT_ENOUGH_MEMORY);p->reader=reader;p->layout=*roots;const wchar_t* directory=l4_journal_reader_directory(reader);if(!directory||wcslen(directory)>=MAX_PATH){setup_acceptance_close(p);return fail(ERROR_BAD_PATHNAME);}wcscpy_s(p->directory,MAX_PATH,directory);if(!open_inputs(p,false,out))return false;if(!setup_acceptance_verify_snapshot(*out,reader,roots,operation)){DWORD e=GetLastError();setup_acceptance_close(*out);*out=NULL;return fail(e);}return true;}
bool setup_acceptance_route(SetupAcceptancePin* p,L4Journal* j,SetupInstalledSource* source){if(!p||!j||j->sequence!=2||!setup_acceptance_bind(p,j,source))return fail(ERROR_INVALID_STATE);L4RemoteHostReceipt ack;FILETIME birth,exit,kernel,user;if(!GetProcessTimes(GetCurrentProcess(),&birth,&exit,&kernel,&user)||!l4_remote_host_load(j,&ack)||ack.pid!=GetCurrentProcessId()||ack.birth!=(((ULONGLONG)birth.dwHighDateTime<<32)|birth.dwLowDateTime)||strcmp(ack.request.version,p->facts.target_version)||strcmp(ack.source_version,p->facts.source_version)||strcmp(ack.arch,p->facts.arch))return fail(ERROR_REVISION_MISMATCH);ULONGLONG seq=0;if(!l4_route_save_trusted(j,p->catalog,p->catalog_size,p->signature,p->signature_size,(utc()-116444736000000000ULL)/10000000ULL,p->facts.source_version,p->facts.source_root,p->facts.target_version,p->facts.arch,p->facts.profile,&seq))return false;L4RoutePlan* route=NULL;bool ok=l4_route_load_trusted(j,seq,&route)&&!memcmp(l4_route_catalog_sha256(route),p->facts.catalog_sha256,32);if(ok)p->facts.catalog_revision=l4_route_revision(route);l4_route_free(route);return ok?true:fail(ERROR_REVISION_MISMATCH);}
bool setup_acceptance_forcepoint(L4Journal* j,const SetupOperationPlan* operation,bool* forced){if(!forced)return fail(ERROR_INVALID_PARAMETER);*forced=false;SetupAcceptancePin* p=NULL;if(!setup_acceptance_open_optional(j,&p))return false;if(!p)return true;bool ok=setup_acceptance_bind_plan(p,j,operation)&&setup_operation_binding(operation,j,setup_operation_sequence(operation))&&setup_acceptance_verify(p,j);if(ok)*forced=p->facts.force_rollback;DWORD e=GetLastError();setup_acceptance_close(p);return ok?true:fail(e?e:ERROR_ACCESS_DENIED);}
static bool write_private(L4Journal* j,const wchar_t* leaf,const void* bytes,DWORD size){wchar_t path[MAX_PATH];if(swprintf_s(path,MAX_PATH,L"%ls\\%ls",j->directory,leaf)<0)return fail(ERROR_FILENAME_EXCED_RANGE);PSECURITY_DESCRIPTOR sd=NULL;if(!ConvertStringSecurityDescriptorToSecurityDescriptorW(L"O:BAD:P(A;;FA;;;SY)(A;;FA;;;BA)",SDDL_REVISION_1,&sd,NULL))return false;SECURITY_ATTRIBUTES sa={sizeof(sa),sd,FALSE};HANDLE previous=NULL;if(!l4_layout_owner_begin(&previous)){LocalFree(sd);return false;}HANDLE f=CreateFileW(path,GENERIC_WRITE,FILE_SHARE_READ,&sa,CREATE_NEW,FILE_FLAG_OPEN_REPARSE_POINT,NULL);bool ok=f!=INVALID_HANDLE_VALUE&&l4_store_write(f,bytes,size)&&FlushFileBuffers(f);DWORD e=GetLastError();if(f!=INVALID_HANDLE_VALUE)CloseHandle(f);if(!l4_layout_owner_end(previous)){ok=false;e=GetLastError();}LocalFree(sd);return ok?true:fail(e?e:ERROR_WRITE_FAULT);}
bool setup_acceptance_stage(L4Journal* j,const char* source,const char* target,const char* arch,const wchar_t* catalog_path,const wchar_t* signature_path,const wchar_t* authorization_path,const wchar_t* authorization_signature_path){if(!j||j->sequence||!source||!target||!arch||!catalog_path||!signature_path||!authorization_path||!authorization_signature_path||!uac_is_elevated()||!original(j)||!version(&j->layout,source)||!version(&j->layout,target)||!strcmp(source,target)||(strcmp(arch,"x86")&&strcmp(arch,"x64")))return fail(ERROR_INVALID_PARAMETER);
 BYTE intent[INTENT_SIZE]={0},*catalog=NULL,*signature=NULL;HANDLE files[2]={NULL,NULL},token=NULL,linked=NULL;DWORD catalog_size=0,signature_size=0,n=0,session=~0u;BYTE user[sizeof(TOKEN_USER)+SECURITY_MAX_SID_SIZE];TOKEN_STATISTICS stats={0};TOKEN_ELEVATION_TYPE elevation=TokenElevationTypeDefault;
 bool ok=OpenProcessToken(GetCurrentProcess(),TOKEN_QUERY,&token)&&GetTokenInformation(token,TokenSessionId,&session,sizeof(session),&n)&&session&&session==WTSGetActiveConsoleSessionId()&&GetTokenInformation(token,TokenElevationType,&elevation,sizeof(elevation),&n);
 if(ok&&elevation==TokenElevationTypeFull){TOKEN_LINKED_TOKEN pair={0};ok=GetTokenInformation(token,TokenLinkedToken,&pair,sizeof(pair),&n);if(ok)linked=pair.LinkedToken;}
 HANDLE identity=linked?linked:token;if(ok)ok=GetTokenInformation(identity,TokenUser,user,sizeof(user),&n)&&GetTokenInformation(identity,TokenStatistics,&stats,sizeof(stats),&n);
 if(ok){PSID sid=((TOKEN_USER*)user)->User.Sid;DWORD sid_size=GetLengthSid(sid);ok=sid_size<=68&&CopySid(68,intent+40,sid);if(ok){l4_store_u32(intent+32,session);l4_store_u32(intent+36,sid_size);l4_store_u32(intent+281,stats.AuthenticationId.LowPart);l4_store_u32(intent+285,(DWORD)stats.AuthenticationId.HighPart);}}
 if(linked)CloseHandle(linked);if(token)CloseHandle(token);
 if(ok)ok=read_file(catalog_path,L4_METADATA_MAX_BYTES,false,&files[0],&catalog,&catalog_size)&&read_file(signature_path,L4_METADATA_SIGNATURE_BYTES,false,&files[1],&signature,&signature_size)&&l4_metadata_verify_trusted(catalog,catalog_size,signature,signature_size,intent+217)&&l4_store_hash(signature,signature_size,NULL,0,intent+249);
 if(ok){const wchar_t* id=wcsrchr(j->directory,L'\\');ok=id&&WideCharToMultiByte(CP_UTF8,WC_ERR_INVALID_CHARS,id+1,-1,(char*)intent+108,37,NULL,NULL);}
 SetupAcceptancePin auth={0};if(ok)ok=read_file(authorization_path,4096,false,&auth.files[3],&auth.authorization,&auth.authorization_size)&&read_file(authorization_signature_path,L4_METADATA_SIGNATURE_BYTES,false,&auth.files[4],&auth.authorization_signature,&auth.authorization_signature_size);
 if(ok){memcpy(intent,"L4ACTR01",8);l4_store_u32(intent+8,1);ULONGLONG now=utc();l4_store_u64(intent+16,now);l4_store_u64(intent+24,now+144000000000ULL);strcpy_s((char*)intent+145,32,source);strcpy_s((char*)intent+177,32,target);strcpy_s((char*)intent+209,8,arch);memcpy(auth.intent,intent,INTENT_SIZE);ok=authorization(&auth,true);if(ok)memcpy(intent,auth.intent,INTENT_SIZE);}
 if(ok)ok=sufficient_lifetime(l4_store_get64(intent+24));
 if(ok)ok=write_private(j,L"acceptance.catalog.json",catalog,catalog_size)&&write_private(j,L"acceptance.catalog.json.sig",signature,signature_size)&&write_private(j,L"acceptance.authorization.json",auth.authorization,auth.authorization_size)&&write_private(j,L"acceptance.authorization.json.sig",auth.authorization_signature,auth.authorization_signature_size)&&write_private(j,L"acceptance.local",intent,INTENT_SIZE);
 for(unsigned i=3;i<5;i++)if(auth.files[i]&&auth.files[i]!=INVALID_HANDLE_VALUE)CloseHandle(auth.files[i]);free(auth.authorization);free(auth.authorization_signature);
 DWORD error=GetLastError();for(unsigned i=0;i<2;i++)if(files[i]&&files[i]!=INVALID_HANDLE_VALUE)CloseHandle(files[i]);free(catalog);free(signature);return ok?true:fail(error?error:ERROR_ACCESS_DENIED);
}
