#include "acceptance_entry.h"
#include "acceptance_local.h"
#include "acceptance_export.h"
#include "remote_policy.h"
#include "../../l4common/journal_internal.h"
#include "../../l4common/active_updater.h"
#include "uac.h"
#include <sddl.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
typedef struct{L4Layout layout;wchar_t source[32],operation[37],host[MAX_PATH],service[80],command[1024],catalog[MAX_PATH],signature[MAX_PATH],authorization[MAX_PATH],authorization_signature[MAX_PATH];char target[32],arch[8];bool bootstrap;} AcceptanceEntry;
static AcceptanceEntry active;static SERVICE_STATUS_HANDLE service_status;
static bool fail(DWORD e){SetLastError(e);return false;}
static bool id(const wchar_t* s){if(!s||wcslen(s)!=36)return false;bool any=false;for(unsigned i=0;i<36;i++){bool dash=i==8||i==13||i==18||i==23;if(dash?s[i]!=L'-':!((s[i]>=L'0'&&s[i]<=L'9')||(s[i]>=L'a'&&s[i]<=L'f')))return false;else if(!dash&&s[i]!=L'0')any=true;}return any;}
static bool command(AcceptanceEntry* e){return l4_layout_resolve(&e->layout,e->source)&&swprintf_s(e->host,MAX_PATH,L"%ls\\setup\\%ls\\l4setup.exe",e->layout.binaries,e->source)>0&&swprintf_s(e->service,80,L"L4Acceptance_%ls",e->operation)>0&&swprintf_s(e->command,1024,L"\"%ls\" --acceptance-bootstrap --source-version %ls --operation %ls --arch %hs",e->host,e->source,e->operation,e->arch)>0;}
static bool private_service(SC_HANDLE service){DWORD size=0;QueryServiceObjectSecurity(service,DACL_SECURITY_INFORMATION,NULL,0,&size);if(GetLastError()!=ERROR_INSUFFICIENT_BUFFER||size<SECURITY_DESCRIPTOR_MIN_LENGTH||size>65536)return fail(ERROR_INVALID_DATA);BYTE* sd=malloc(size);if(!sd)return fail(ERROR_NOT_ENOUGH_MEMORY);BOOL present=FALSE,defaulted=FALSE;PACL acl=NULL;SECURITY_DESCRIPTOR_CONTROL control=0;DWORD revision=0;bool sys=false,ba=false;
 bool ok=QueryServiceObjectSecurity(service,DACL_SECURITY_INFORMATION,sd,size,&size)&&GetSecurityDescriptorControl(sd,&control,&revision)&&(control&SE_DACL_PROTECTED)&&GetSecurityDescriptorDacl(sd,&present,&acl,&defaulted)&&present&&acl&&acl->AceCount==2;
 for(unsigned i=0;ok&&i<acl->AceCount;i++){void* raw=NULL;ok=GetAce(acl,i,&raw)!=0;if(!ok)break;ACCESS_ALLOWED_ACE* a=raw;ok=a->Header.AceType==ACCESS_ALLOWED_ACE_TYPE&&!a->Header.AceFlags&&(a->Mask==GENERIC_ALL||a->Mask==SERVICE_ALL_ACCESS);if(ok&&IsWellKnownSid(&a->SidStart,WinLocalSystemSid))sys=true;else if(ok&&IsWellKnownSid(&a->SidStart,WinBuiltinAdministratorsSid))ba=true;else ok=false;}free(sd);return ok&&sys&&ba?true:fail(ERROR_ACCESS_DENIED);
}
static bool fingerprint(SC_HANDLE service,const AcceptanceEntry* e){DWORD n=0;QueryServiceConfigW(service,NULL,0,&n);if(GetLastError()!=ERROR_INSUFFICIENT_BUFFER||n<sizeof(QUERY_SERVICE_CONFIGW)||n>65536)return fail(ERROR_INVALID_DATA);QUERY_SERVICE_CONFIGW* c=malloc(n);if(!c)return fail(ERROR_NOT_ENOUGH_MEMORY);wchar_t display[96];swprintf_s(display,96,L"L4 acceptance %ls",e->operation);bool ok=QueryServiceConfigW(service,c,n,&n)&&c->lpBinaryPathName&&!wcscmp(c->lpBinaryPathName,e->command)&&c->lpDisplayName&&!wcscmp(c->lpDisplayName,display)&&c->lpServiceStartName&&!_wcsicmp(c->lpServiceStartName,L"LocalSystem")&&c->dwServiceType==SERVICE_WIN32_OWN_PROCESS&&c->dwStartType==SERVICE_DEMAND_START&&c->dwErrorControl==SERVICE_ERROR_NORMAL&&(!c->lpDependencies||!*c->lpDependencies)&&(!c->lpLoadOrderGroup||!*c->lpLoadOrderGroup);DWORD error=GetLastError();free(c);return ok?private_service(service):fail(error?error:ERROR_REVISION_MISMATCH);}
static bool self(const AcceptanceEntry* e){wchar_t module[MAX_PATH];if(!GetModuleFileNameW(NULL,module,MAX_PATH)||wcscmp(module,e->host))return fail(ERROR_ACCESS_DENIED);SC_HANDLE manager=OpenSCManagerW(NULL,NULL,SC_MANAGER_CONNECT);if(!manager)return false;SC_HANDLE service=OpenServiceW(manager,e->service,SERVICE_QUERY_CONFIG|SERVICE_QUERY_STATUS|READ_CONTROL);SERVICE_STATUS_PROCESS status={0};DWORD n=0;bool ok=service&&fingerprint(service,e)&&QueryServiceStatusEx(service,SC_STATUS_PROCESS_INFO,(BYTE*)&status,sizeof(status),&n)&&status.dwCurrentState==SERVICE_RUNNING&&status.dwProcessId==GetCurrentProcessId();DWORD error=GetLastError();if(service)CloseServiceHandle(service);CloseServiceHandle(manager);return ok?true:fail(error?error:ERROR_ACCESS_DENIED);}
static DWORD execute(const AcceptanceEntry* e){L4Journal* j=NULL;SetupInstalledSource* source=NULL;SetupAcceptancePin* acceptance=NULL;L4RemoteHost* host=NULL;L4ActiveUpdater* updater=NULL;DWORD error=ERROR_NOT_READY;L4RemoteRequest request;L4RemoteHostReceipt ack;
#define REQUIRE(x) do{SetLastError(0);if(!(x)){error=GetLastError()?GetLastError():ERROR_NOT_READY;goto done;}}while(0)
 REQUIRE(self(e));REQUIRE(l4_journal_open(&e->layout,e->operation,false,&j));if(j->sequence){error=ERROR_INVALID_STATE;goto done;}REQUIRE(setup_acceptance_open_optional(j,&acceptance));if(!acceptance){error=ERROR_ACCESS_DENIED;goto done;}REQUIRE(setup_installed_source_open(j,&source));REQUIRE(setup_acceptance_bind(acceptance,j,source));
 REQUIRE(l4_active_updater_open(j,&updater));const L4ActiveUpdaterInfo* image=l4_active_updater_info(updater);const SetupRootManifest* root=setup_installed_source_updater_root(source);if(!image||strcmp(image->version,setup_installed_source_updater_version(source))||wcscmp(l4_active_updater_path(updater),e->host)){error=ERROR_REVISION_MISMATCH;goto done;}
 REQUIRE(setup_signed_executable(l4_active_updater_file(updater),e->host,setup_root_publisher(root)));REQUIRE(setup_installed_source_verify(source));REQUIRE(setup_acceptance_prelaunch(acceptance,j));const SetupAcceptanceFacts* facts=setup_acceptance_facts(acceptance);if(!facts){error=ERROR_INVALID_DATA;goto done;}
 REQUIRE(l4_remote_request_save(j,L4_REMOTE_SUITE,facts->target_version,&request));setup_acceptance_close(acceptance);acceptance=NULL;setup_installed_source_close(source);source=NULL;
 REQUIRE(l4_remote_host_launch_local(&j,e->arch,180000,&host,&ack));DWORD child=STILL_ACTIVE;REQUIRE(l4_remote_host_wait(host,SETUP_ACCEPTANCE_INNER_WAIT_MS,&child));
 /* Diagnostic exit cannot replace actual protected102/108+103/clear evidence. */
 REQUIRE(setup_acceptance_export(&e->layout,e->operation));error=0;
done:setup_acceptance_close(acceptance);setup_installed_source_close(source);l4_active_updater_close(updater);l4_remote_host_close(host);l4_journal_close(j);return error;
#undef REQUIRE
}
static void report(DWORD state,DWORD error){SERVICE_STATUS s={0};s.dwServiceType=SERVICE_WIN32_OWN_PROCESS;s.dwCurrentState=state;if(error){s.dwWin32ExitCode=ERROR_SERVICE_SPECIFIC_ERROR;s.dwServiceSpecificExitCode=error;}SetServiceStatus(service_status,&s);}
static DWORD WINAPI control(DWORD code,DWORD event,void* data,void* context){(void)code;(void)event;(void)data;(void)context;return ERROR_CALL_NOT_IMPLEMENTED;}
static void WINAPI service_main(DWORD argc,wchar_t** argv){(void)argc;(void)argv;service_status=RegisterServiceCtrlHandlerExW(active.service,control,NULL);if(!service_status)return;report(SERVICE_RUNNING,0);report(SERVICE_STOPPED,execute(&active));}
static DWORD launch_bootstrap(const AcceptanceEntry* e){DWORD result=ERROR_NOT_READY;SC_HANDLE manager=OpenSCManagerW(NULL,NULL,SC_MANAGER_CONNECT|SC_MANAGER_CREATE_SERVICE);if(!manager)return GetLastError();wchar_t display[96];swprintf_s(display,96,L"L4 acceptance %ls",e->operation);SC_HANDLE service=CreateServiceW(manager,e->service,display,SERVICE_ALL_ACCESS,SERVICE_WIN32_OWN_PROCESS,SERVICE_DEMAND_START,SERVICE_ERROR_NORMAL,e->command,NULL,NULL,NULL,L"LocalSystem",NULL);if(!service){result=GetLastError();CloseServiceHandle(manager);return result;}
 PSECURITY_DESCRIPTOR sd=NULL;bool ok=ConvertStringSecurityDescriptorToSecurityDescriptorW(L"D:P(A;;GA;;;SY)(A;;GA;;;BA)",SDDL_REVISION_1,&sd,NULL)&&SetServiceObjectSecurity(service,DACL_SECURITY_INFORMATION|PROTECTED_DACL_SECURITY_INFORMATION,sd)&&fingerprint(service,e)&&StartServiceW(service,0,NULL);if(sd)LocalFree(sd);if(!ok){result=GetLastError()?GetLastError():ERROR_ACCESS_DENIED;goto done;}
 ULONGLONG end=GetTickCount64()+SETUP_ACCEPTANCE_OUTER_WAIT_MS;for(;;){SERVICE_STATUS_PROCESS status;DWORD n=0;if(!fingerprint(service,e)||!QueryServiceStatusEx(service,SC_STATUS_PROCESS_INFO,(BYTE*)&status,sizeof(status),&n)){result=GetLastError();break;}if(status.dwCurrentState==SERVICE_STOPPED){result=status.dwWin32ExitCode==ERROR_SERVICE_SPECIFIC_ERROR?status.dwServiceSpecificExitCode:status.dwWin32ExitCode;break;}if(GetTickCount64()>=end){result=ERROR_TIMEOUT;break;}Sleep(250);}
done:;SERVICE_STATUS_PROCESS stopped={0};DWORD n=0;if(fingerprint(service,e)&&QueryServiceStatusEx(service,SC_STATUS_PROCESS_INFO,(BYTE*)&stopped,sizeof(stopped),&n)&&stopped.dwCurrentState==SERVICE_STOPPED)DeleteService(service);CloseServiceHandle(service);CloseServiceHandle(manager);return result;
}
bool setup_acceptance_entry(int argc,wchar_t** argv,DWORD* result){if(argc<2||(wcscmp(argv[1],L"--acceptance-local")&&wcscmp(argv[1],L"--acceptance-bootstrap")))return false;if(!result)return true;*result=ERROR_INVALID_PARAMETER;AcceptanceEntry e={0};e.bootstrap=!wcscmp(argv[1],L"--acceptance-bootstrap");unsigned seen=0;
 for(int i=2;i<argc;i+=2){if(i+1>=argc)return true;unsigned bit=0;const wchar_t* key=argv[i],*value=argv[i+1];if(!wcscmp(key,L"--source-version")){bit=1;if(wcslen(value)>=32)return true;wcscpy_s(e.source,32,value);}else if(!wcscmp(key,L"--operation")){bit=2;if(!id(value))return true;wcscpy_s(e.operation,37,value);}else if(!wcscmp(key,L"--arch")){bit=4;if(wcscmp(value,L"x86")&&wcscmp(value,L"x64"))return true;strcpy_s(e.arch,8,!wcscmp(value,L"x86")?"x86":"x64");}
 else if(!e.bootstrap&&!wcscmp(key,L"--target-version")){bit=8;if(!WideCharToMultiByte(CP_UTF8,WC_ERR_INVALID_CHARS,value,-1,e.target,32,NULL,NULL))return true;}
 else{wchar_t* destination=NULL;if(!e.bootstrap&&!wcscmp(key,L"--trial-catalog")){bit=16;destination=e.catalog;}else if(!e.bootstrap&&!wcscmp(key,L"--trial-signature")){bit=32;destination=e.signature;}else if(!e.bootstrap&&!wcscmp(key,L"--intent")){bit=64;destination=e.authorization;}else if(!e.bootstrap&&!wcscmp(key,L"--intent-signature")){bit=128;destination=e.authorization_signature;}else return true;if(wcslen(value)>=MAX_PATH||wcslen(value)<4||value[1]!=L':'||value[2]!=L'\\'||wcschr(value+2,L':'))return true;wcscpy_s(destination,MAX_PATH,value);}
 if(seen&bit)return true;seen|=bit;}
 if(seen!=(e.bootstrap?7u:255u)||!command(&e))return true;wchar_t module[MAX_PATH];if(!GetModuleFileNameW(NULL,module,MAX_PATH)||wcscmp(module,e.host)){*result=ERROR_ACCESS_DENIED;return true;}
 if(e.bootstrap){active=e;SERVICE_TABLE_ENTRYW table[]={{active.service,service_main},{NULL,NULL}};*result=StartServiceCtrlDispatcherW(table)?0:GetLastError();return true;}
 if(!uac_is_elevated()){*result=ERROR_ACCESS_DENIED;return true;}L4Journal* j=NULL;char source[32];if(!WideCharToMultiByte(CP_UTF8,WC_ERR_INVALID_CHARS,e.source,-1,source,32,NULL,NULL)||!l4_journal_open(&e.layout,e.operation,true,&j)){*result=GetLastError();return true;}
 bool staged=setup_acceptance_stage(j,source,e.target,e.arch,e.catalog,e.signature,e.authorization,e.authorization_signature);*result=staged?0:GetLastError();l4_journal_close(j);if(staged)*result=launch_bootstrap(&e);
 printf("{\"operation_id\":\"%ls\",\"local_acceptance_launch\":true,\"error\":%lu}\n",e.operation,*result);return true;
}
