#pragma once

#define L4SETUP_VERSION_MAJOR 1
#define L4SETUP_VERSION_MINOR 7
#define L4SETUP_VERSION_PATCH 4
#define L4SETUP_VERSION_BUILD 0
#define L4SETUP_VERSION_STRING "1.7.4"
#define L4SETUP_VERSION_WSTRING L"1.7.4"
