#pragma once

#define L4SETUP_VERSION_MAJOR 1
#define L4SETUP_VERSION_MINOR 10
#define L4SETUP_VERSION_PATCH 2
#define L4SETUP_VERSION_BUILD 0
#define L4SETUP_VERSION_STRING "1.10.2"
#define L4SETUP_VERSION_WSTRING L"1.10.2"
