#pragma once

#define L4SETUP_VERSION_MAJOR 1
#define L4SETUP_VERSION_MINOR 9
#define L4SETUP_VERSION_PATCH 5
#define L4SETUP_VERSION_BUILD 0
#define L4SETUP_VERSION_STRING "1.9.5"
#define L4SETUP_VERSION_WSTRING L"1.9.5"
