"""Initial payment flow tables

Revision ID: 001
Revises: 
Create Date: 2026-08-15

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Orgs table
    op.create_table('orgs',
        sa.Column('org_id', sa.Integer(), nullable=False),
        sa.Column('org_name', sa.String(150), nullable=False),
        sa.Column('name', sa.String(150), nullable=False),
        sa.Column('status', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('org_id')
    )
    op.create_index('idx_orgs_status', 'orgs', ['status'])
    
    # TSP table
    op.create_table('tsp',
        sa.Column('tsp_id', sa.Integer(), nullable=False),
        sa.Column('tsp_code', sa.Integer(), nullable=False),
        sa.Column('tsp_name', sa.String(255), nullable=False),
        sa.PrimaryKeyConstraint('tsp_id'),
        sa.UniqueConstraint('tsp_code')
    )
    op.create_index('idx_tsp_code', 'tsp', ['tsp_code'])
    
    # TSP Parameter Codes table
    op.create_table('tsp_parameter_codes',
        sa.Column('param_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('prototypenumber', sa.Integer(), nullable=False),
        sa.Column('parameter_code', sa.Integer(), nullable=False),
        sa.Column('code_description', sa.String(255), nullable=True),
        sa.PrimaryKeyConstraint('param_id'),
        sa.UniqueConstraint('prototypenumber', 'parameter_code', name='uq_prototype_param_code')
    )
    op.create_index('idx_tsp_param_prototype', 'tsp_parameter_codes', ['prototypenumber'])
    
    # Terminals table (if not exists)
    op.create_table('terminals',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('device_id', sa.Integer(), nullable=False),
        sa.Column('sn', sa.String(100), nullable=False),
        sa.Column('cert_serial', sa.String(100), nullable=True),
        sa.Column('org_id', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('device_id'),
        sa.UniqueConstraint('sn')
    )
    op.create_index('idx_terminals_sn', 'terminals', ['sn'])
    op.create_index('idx_terminals_cert_serial', 'terminals', ['cert_serial'])
    op.create_index('idx_terminals_org_id', 'terminals', ['org_id'])
    
    # Payments table
    op.create_table('payments',
        sa.Column('paym_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('paym_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('paym_amount', sa.BigInteger(), nullable=False),
        sa.Column('paym_ext_id', sa.String(20), nullable=False),
        sa.Column('paym_tsp_code', sa.Integer(), nullable=False),
        sa.Column('terminal_id', sa.Integer(), nullable=False),
        sa.Column('org_id', sa.Integer(), nullable=False),
        sa.Column('paym_state', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('paym_id'),
        sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id']),
        sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'])
    )
    op.create_index('idx_payments_terminal_id', 'payments', ['terminal_id'])
    op.create_index('idx_payments_org_id', 'payments', ['org_id'])
    op.create_index('idx_payments_ext_id', 'payments', ['paym_ext_id'])
    op.create_index('idx_payments_tsp_code', 'payments', ['paym_tsp_code'])
    op.create_index('idx_payments_datetime', 'payments', ['paym_datetime'])
    
    # Payment Params table
    op.create_table('payment_params',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('paym_id', sa.Integer(), nullable=False),
        sa.Column('param_id', sa.Integer(), nullable=False),
        sa.Column('param_value', sa.String(2000), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['paym_id'], ['payments.paym_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['param_id'], ['tsp_parameter_codes.param_id'])
    )
    op.create_index('idx_payment_params_paym_id', 'payment_params', ['paym_id'])
    op.create_index('idx_payment_params_param_id', 'payment_params', ['param_id'])
    
    # Balance Terminal TSP table
    op.create_table('balance_terminal_tsp',
        sa.Column('rec_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('int_day', sa.Integer(), nullable=False),
        sa.Column('org_id', sa.Integer(), nullable=False),
        sa.Column('terminal_id', sa.Integer(), nullable=False),
        sa.Column('tsp_id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.BigInteger(), nullable=True),
        sa.Column('count', sa.Integer(), nullable=True),
        sa.Column('update_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('rec_id'),
        sa.UniqueConstraint('int_day', 'terminal_id', 'tsp_id', name='uq_balance_day_terminal_tsp'),
        sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id']),
        sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id']),
        sa.ForeignKeyConstraint(['tsp_id'], ['tsp.tsp_id'])
    )
    op.create_index('idx_balance_int_day', 'balance_terminal_tsp', ['int_day'])
    op.create_index('idx_balance_terminal_id', 'balance_terminal_tsp', ['terminal_id'])
    op.create_index('idx_balance_tsp_id', 'balance_terminal_tsp', ['tsp_id'])
    op.create_index('idx_balance_org_id', 'balance_terminal_tsp', ['org_id'])
    
    # Existing tables (if not exists)
    op.create_table('org_statuses',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('org_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(20), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('org_id')
    )
    
    op.create_table('licenses',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('terminal_id', sa.Integer(), nullable=False),
        sa.Column('org_id', sa.Integer(), nullable=False),
        sa.Column('license_type', sa.String(50), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('balance', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], ondelete='CASCADE')
    )
    op.create_index('idx_licenses_terminal_id', 'licenses', ['terminal_id'])
    op.create_index('idx_licenses_org_id', 'licenses', ['org_id'])
    op.create_index('idx_licenses_expires_at', 'licenses', ['expires_at'])
    
    op.create_table('gate_gauge_records',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('device_id', sa.Integer(), nullable=False),
        sa.Column('sn', sa.String(100), nullable=True),
        sa.Column('gauge_data', sa.JSON(), nullable=False),
        sa.Column('raw_data', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gauge_device_id', 'gate_gauge_records', ['device_id'])
    op.create_index('idx_gauge_created_at', 'gate_gauge_records', ['created_at'])
    
    op.create_table('tech_gate_records',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('device_id', sa.Integer(), nullable=False),
        sa.Column('sn', sa.String(100), nullable=True),
        sa.Column('function_name', sa.String(50), nullable=False),
        sa.Column('request_data', sa.JSON(), nullable=False),
        sa.Column('raw_params', sa.Text(), nullable=True),
        sa.Column('response_status', sa.String(20), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_techgate_device_id', 'tech_gate_records', ['device_id'])
    op.create_index('idx_techgate_function', 'tech_gate_records', ['function_name'])
    op.create_index('idx_techgate_created_at', 'tech_gate_records', ['created_at'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tech_gate_records')
    op.drop_table('gate_gauge_records')
    op.drop_table('licenses')
    op.drop_table('org_statuses')
    op.drop_table('balance_terminal_tsp')
    op.drop_table('payment_params')
    op.drop_table('payments')
    op.drop_table('terminals')
    op.drop_table('tsp_parameter_codes')
    op.drop_table('tsp')
    op.drop_table('orgs')
    # ### end Alembic commands ###
