//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessorService.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PostomatsEntities : DbContext
    {
        public PostomatsEntities()
            : base("name=PostomatsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Messages> tb_Messages { get; set; }
        public virtual DbSet<tb_Payments> tb_Payments { get; set; }
        public virtual DbSet<tb_Tsp> tb_Tsp { get; set; }
        public virtual DbSet<tb_TspPayParameters> tb_TspPayParameters { get; set; }
    }
}
