//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessorService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Messages
    {
        public int Id { get; set; }
        public string Phone { get; set; }
        public string Text { get; set; }
        public int StatusId { get; set; }
        public System.DateTime StatusDateTime { get; set; }
        public int StatusUserId { get; set; }
        public string StatusComment { get; set; }
        public System.DateTime DateTimeAdd { get; set; }
        public Nullable<int> MessageTemplateId { get; set; }
        public Nullable<int> SourceTypeId { get; set; }
        public Nullable<int> SourceId { get; set; }
    }
}
