//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessorService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Payments
    {
        public int Id { get; set; }
        public string PaymExtId { get; set; }
        public int SourceTypeId { get; set; }
        public int SourceId { get; set; }
        public decimal Sum { get; set; }
        public int StatusId { get; set; }
        public System.DateTime StatusDateTime { get; set; }
        public int StatusUserId { get; set; }
        public string StatusComment { get; set; }
        public string Phone { get; set; }
        public int PaymentPurposeId { get; set; }
        public int PayTypeId { get; set; }
        public System.DateTime DateTimeCreate { get; set; }
        public int PostomatId { get; set; }
    }
}
