//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessorService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Tsp
    {
        public int Id { get; set; }
        public int Code { get; set; }
        public string ShortName { get; set; }
        public string Fullname { get; set; }
        public string Inn { get; set; }
        public string Dogovor { get; set; }
        public bool IsActive { get; set; }
    }
}
