//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GisMarkers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EBSEntities : DbContext
    {
        public EBSEntities()
            : base("name=EBSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Locations> tb_Locations { get; set; }
        public virtual DbSet<ts_LocationTypes> ts_LocationTypes { get; set; }
        public virtual DbSet<ymapapiv2_markers_cat> ymapapiv2_markers_cat { get; set; }
    }
}
