//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GisMarkers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ymapapiv2_markers_cat
    {
        public int id { get; set; }
        public string name { get; set; }
        public string hintText { get; set; }
        public string balloonText { get; set; }
        public string type { get; set; }
        public string lat { get; set; }
        public string lon { get; set; }
    }
}
