//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.3053
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="MessageProcessorSoap", Namespace="http://tempuri.org/")]
public partial class MessageProcessor : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback PaySystemsTimeOutOperationCompleted;
    
    private System.Threading.SendOrPostCallback ModuleNameOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetAvailableJobsOperationCompleted;
    
    private System.Threading.SendOrPostCallback XmlPaymentInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback ProcessMessageOperationCompleted;
    
    private System.Threading.SendOrPostCallback UpdatePaymentOperationCompleted;
    
    private System.Threading.SendOrPostCallback AssignMessageOperationCompleted;
    
    private System.Threading.SendOrPostCallback RunPaymentFromCustomSPOperationCompleted;
    
    private System.Threading.SendOrPostCallback AssignMessageParamsOperationCompleted;
    
    /// <remarks/>
    public MessageProcessor(string url) {
        this.Url = url;
    }
    
    /// <remarks/>
    public event PaySystemsTimeOutCompletedEventHandler PaySystemsTimeOutCompleted;
    
    /// <remarks/>
    public event ModuleNameCompletedEventHandler ModuleNameCompleted;
    
    /// <remarks/>
    public event GetAvailableJobsCompletedEventHandler GetAvailableJobsCompleted;
    
    /// <remarks/>
    public event XmlPaymentInfoCompletedEventHandler XmlPaymentInfoCompleted;
    
    /// <remarks/>
    public event ProcessMessageCompletedEventHandler ProcessMessageCompleted;
    
    /// <remarks/>
    public event UpdatePaymentCompletedEventHandler UpdatePaymentCompleted;
    
    /// <remarks/>
    public event AssignMessageCompletedEventHandler AssignMessageCompleted;
    
    /// <remarks/>
    public event RunPaymentFromCustomSPCompletedEventHandler RunPaymentFromCustomSPCompleted;
    
    /// <remarks/>
    public event AssignMessageParamsCompletedEventHandler AssignMessageParamsCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PaySystemsTimeOut", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public short PaySystemsTimeOut() {
        object[] results = this.Invoke("PaySystemsTimeOut", new object[0]);
        return ((short)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginPaySystemsTimeOut(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("PaySystemsTimeOut", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public short EndPaySystemsTimeOut(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((short)(results[0]));
    }
    
    /// <remarks/>
    public void PaySystemsTimeOutAsync() {
        this.PaySystemsTimeOutAsync(null);
    }
    
    /// <remarks/>
    public void PaySystemsTimeOutAsync(object userState) {
        if ((this.PaySystemsTimeOutOperationCompleted == null)) {
            this.PaySystemsTimeOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPaySystemsTimeOutOperationCompleted);
        }
        this.InvokeAsync("PaySystemsTimeOut", new object[0], this.PaySystemsTimeOutOperationCompleted, userState);
    }
    
    private void OnPaySystemsTimeOutOperationCompleted(object arg) {
        if ((this.PaySystemsTimeOutCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.PaySystemsTimeOutCompleted(this, new PaySystemsTimeOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModuleName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string ModuleName() {
        object[] results = this.Invoke("ModuleName", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginModuleName(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ModuleName", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndModuleName(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void ModuleNameAsync() {
        this.ModuleNameAsync(null);
    }
    
    /// <remarks/>
    public void ModuleNameAsync(object userState) {
        if ((this.ModuleNameOperationCompleted == null)) {
            this.ModuleNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModuleNameOperationCompleted);
        }
        this.InvokeAsync("ModuleName", new object[0], this.ModuleNameOperationCompleted, userState);
    }
    
    private void OnModuleNameOperationCompleted(object arg) {
        if ((this.ModuleNameCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ModuleNameCompleted(this, new ModuleNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAvailableJobs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public long GetAvailableJobs() {
        object[] results = this.Invoke("GetAvailableJobs", new object[0]);
        return ((long)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetAvailableJobs(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetAvailableJobs", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public long EndGetAvailableJobs(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((long)(results[0]));
    }
    
    /// <remarks/>
    public void GetAvailableJobsAsync() {
        this.GetAvailableJobsAsync(null);
    }
    
    /// <remarks/>
    public void GetAvailableJobsAsync(object userState) {
        if ((this.GetAvailableJobsOperationCompleted == null)) {
            this.GetAvailableJobsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAvailableJobsOperationCompleted);
        }
        this.InvokeAsync("GetAvailableJobs", new object[0], this.GetAvailableJobsOperationCompleted, userState);
    }
    
    private void OnGetAvailableJobsOperationCompleted(object arg) {
        if ((this.GetAvailableJobsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetAvailableJobsCompleted(this, new GetAvailableJobsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XmlPaymentInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string XmlPaymentInfo(string paymextid, int serial_number) {
        object[] results = this.Invoke("XmlPaymentInfo", new object[] {
                    paymextid,
                    serial_number});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginXmlPaymentInfo(string paymextid, int serial_number, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("XmlPaymentInfo", new object[] {
                    paymextid,
                    serial_number}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndXmlPaymentInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void XmlPaymentInfoAsync(string paymextid, int serial_number) {
        this.XmlPaymentInfoAsync(paymextid, serial_number, null);
    }
    
    /// <remarks/>
    public void XmlPaymentInfoAsync(string paymextid, int serial_number, object userState) {
        if ((this.XmlPaymentInfoOperationCompleted == null)) {
            this.XmlPaymentInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXmlPaymentInfoOperationCompleted);
        }
        this.InvokeAsync("XmlPaymentInfo", new object[] {
                    paymextid,
                    serial_number}, this.XmlPaymentInfoOperationCompleted, userState);
    }
    
    private void OnXmlPaymentInfoOperationCompleted(object arg) {
        if ((this.XmlPaymentInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.XmlPaymentInfoCompleted(this, new XmlPaymentInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string ProcessMessage(string Function, string PaymExtId, string PaymSubjTp, string Amount, string Params, string Serial, string TotalSum, string Signature, string userid) {
        object[] results = this.Invoke("ProcessMessage", new object[] {
                    Function,
                    PaymExtId,
                    PaymSubjTp,
                    Amount,
                    Params,
                    Serial,
                    TotalSum,
                    Signature,
                    userid});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginProcessMessage(string Function, string PaymExtId, string PaymSubjTp, string Amount, string Params, string Serial, string TotalSum, string Signature, string userid, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ProcessMessage", new object[] {
                    Function,
                    PaymExtId,
                    PaymSubjTp,
                    Amount,
                    Params,
                    Serial,
                    TotalSum,
                    Signature,
                    userid}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndProcessMessage(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void ProcessMessageAsync(string Function, string PaymExtId, string PaymSubjTp, string Amount, string Params, string Serial, string TotalSum, string Signature, string userid) {
        this.ProcessMessageAsync(Function, PaymExtId, PaymSubjTp, Amount, Params, Serial, TotalSum, Signature, userid, null);
    }
    
    /// <remarks/>
    public void ProcessMessageAsync(string Function, string PaymExtId, string PaymSubjTp, string Amount, string Params, string Serial, string TotalSum, string Signature, string userid, object userState) {
        if ((this.ProcessMessageOperationCompleted == null)) {
            this.ProcessMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessMessageOperationCompleted);
        }
        this.InvokeAsync("ProcessMessage", new object[] {
                    Function,
                    PaymExtId,
                    PaymSubjTp,
                    Amount,
                    Params,
                    Serial,
                    TotalSum,
                    Signature,
                    userid}, this.ProcessMessageOperationCompleted, userState);
    }
    
    private void OnProcessMessageOperationCompleted(object arg) {
        if ((this.ProcessMessageCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ProcessMessageCompleted(this, new ProcessMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdatePayment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string UpdatePayment(string PaymentID, string Function, string PaymExtId, string PaymSubjTp, string Amount, string Params, string Serial, string TotalSum, string Signature, string userid) {
        object[] results = this.Invoke("UpdatePayment", new object[] {
                    PaymentID,
                    Function,
                    PaymExtId,
                    PaymSubjTp,
                    Amount,
                    Params,
                    Serial,
                    TotalSum,
                    Signature,
                    userid});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdatePayment(string PaymentID, string Function, string PaymExtId, string PaymSubjTp, string Amount, string Params, string Serial, string TotalSum, string Signature, string userid, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UpdatePayment", new object[] {
                    PaymentID,
                    Function,
                    PaymExtId,
                    PaymSubjTp,
                    Amount,
                    Params,
                    Serial,
                    TotalSum,
                    Signature,
                    userid}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndUpdatePayment(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void UpdatePaymentAsync(string PaymentID, string Function, string PaymExtId, string PaymSubjTp, string Amount, string Params, string Serial, string TotalSum, string Signature, string userid) {
        this.UpdatePaymentAsync(PaymentID, Function, PaymExtId, PaymSubjTp, Amount, Params, Serial, TotalSum, Signature, userid, null);
    }
    
    /// <remarks/>
    public void UpdatePaymentAsync(string PaymentID, string Function, string PaymExtId, string PaymSubjTp, string Amount, string Params, string Serial, string TotalSum, string Signature, string userid, object userState) {
        if ((this.UpdatePaymentOperationCompleted == null)) {
            this.UpdatePaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePaymentOperationCompleted);
        }
        this.InvokeAsync("UpdatePayment", new object[] {
                    PaymentID,
                    Function,
                    PaymExtId,
                    PaymSubjTp,
                    Amount,
                    Params,
                    Serial,
                    TotalSum,
                    Signature,
                    userid}, this.UpdatePaymentOperationCompleted, userState);
    }
    
    private void OnUpdatePaymentOperationCompleted(object arg) {
        if ((this.UpdatePaymentCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdatePaymentCompleted(this, new UpdatePaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AssignMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void AssignMessage(int PaymentID) {
        this.Invoke("AssignMessage", new object[] {
                    PaymentID});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginAssignMessage(int PaymentID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("AssignMessage", new object[] {
                    PaymentID}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndAssignMessage(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void AssignMessageAsync(int PaymentID) {
        this.AssignMessageAsync(PaymentID, null);
    }
    
    /// <remarks/>
    public void AssignMessageAsync(int PaymentID, object userState) {
        if ((this.AssignMessageOperationCompleted == null)) {
            this.AssignMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAssignMessageOperationCompleted);
        }
        this.InvokeAsync("AssignMessage", new object[] {
                    PaymentID}, this.AssignMessageOperationCompleted, userState);
    }
    
    private void OnAssignMessageOperationCompleted(object arg) {
        if ((this.AssignMessageCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AssignMessageCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RunPaymentFromCustomSP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void RunPaymentFromCustomSP(string name_sp) {
        this.Invoke("RunPaymentFromCustomSP", new object[] {
                    name_sp});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginRunPaymentFromCustomSP(string name_sp, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("RunPaymentFromCustomSP", new object[] {
                    name_sp}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndRunPaymentFromCustomSP(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void RunPaymentFromCustomSPAsync(string name_sp) {
        this.RunPaymentFromCustomSPAsync(name_sp, null);
    }
    
    /// <remarks/>
    public void RunPaymentFromCustomSPAsync(string name_sp, object userState) {
        if ((this.RunPaymentFromCustomSPOperationCompleted == null)) {
            this.RunPaymentFromCustomSPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRunPaymentFromCustomSPOperationCompleted);
        }
        this.InvokeAsync("RunPaymentFromCustomSP", new object[] {
                    name_sp}, this.RunPaymentFromCustomSPOperationCompleted, userState);
    }
    
    private void OnRunPaymentFromCustomSPOperationCompleted(object arg) {
        if ((this.RunPaymentFromCustomSPCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RunPaymentFromCustomSPCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AssignMessageParams", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void AssignMessageParams(int paym_id, string PaymExtId, int PaymSubjTp, long paym_amount, int serial_number, int totalsum, string url, string rek, int ps_id) {
        this.Invoke("AssignMessageParams", new object[] {
                    paym_id,
                    PaymExtId,
                    PaymSubjTp,
                    paym_amount,
                    serial_number,
                    totalsum,
                    url,
                    rek,
                    ps_id});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginAssignMessageParams(int paym_id, string PaymExtId, int PaymSubjTp, long paym_amount, int serial_number, int totalsum, string url, string rek, int ps_id, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("AssignMessageParams", new object[] {
                    paym_id,
                    PaymExtId,
                    PaymSubjTp,
                    paym_amount,
                    serial_number,
                    totalsum,
                    url,
                    rek,
                    ps_id}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndAssignMessageParams(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void AssignMessageParamsAsync(int paym_id, string PaymExtId, int PaymSubjTp, long paym_amount, int serial_number, int totalsum, string url, string rek, int ps_id) {
        this.AssignMessageParamsAsync(paym_id, PaymExtId, PaymSubjTp, paym_amount, serial_number, totalsum, url, rek, ps_id, null);
    }
    
    /// <remarks/>
    public void AssignMessageParamsAsync(int paym_id, string PaymExtId, int PaymSubjTp, long paym_amount, int serial_number, int totalsum, string url, string rek, int ps_id, object userState) {
        if ((this.AssignMessageParamsOperationCompleted == null)) {
            this.AssignMessageParamsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAssignMessageParamsOperationCompleted);
        }
        this.InvokeAsync("AssignMessageParams", new object[] {
                    paym_id,
                    PaymExtId,
                    PaymSubjTp,
                    paym_amount,
                    serial_number,
                    totalsum,
                    url,
                    rek,
                    ps_id}, this.AssignMessageParamsOperationCompleted, userState);
    }
    
    private void OnAssignMessageParamsOperationCompleted(object arg) {
        if ((this.AssignMessageParamsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AssignMessageParamsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void PaySystemsTimeOutCompletedEventHandler(object sender, PaySystemsTimeOutCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PaySystemsTimeOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal PaySystemsTimeOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public short Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((short)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void ModuleNameCompletedEventHandler(object sender, ModuleNameCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ModuleNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ModuleNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetAvailableJobsCompletedEventHandler(object sender, GetAvailableJobsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetAvailableJobsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetAvailableJobsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public long Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((long)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void XmlPaymentInfoCompletedEventHandler(object sender, XmlPaymentInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlPaymentInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal XmlPaymentInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void ProcessMessageCompletedEventHandler(object sender, ProcessMessageCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ProcessMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ProcessMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void UpdatePaymentCompletedEventHandler(object sender, UpdatePaymentCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UpdatePaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal UpdatePaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void AssignMessageCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void RunPaymentFromCustomSPCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void AssignMessageParamsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
