/* Real RSA signatures + real protected files; no SYSTEM/live installation. */
#include "../src/bootstrap_receipt.h"
#include "../src/recovery_receipt.c"
static unsigned checks,failures;
#define CHECK(x) do{++checks;if(!(x)){++failures;printf("FAIL bootstrap %u: %s (%lu)\n",__LINE__,#x,GetLastError());}}while(0)
static BCRYPT_KEY_HANDLE key;
static BYTE public_key[411],signature[384];
static char key_id[65],json[4096];
static void sign_doc(void){BYTE digest[32];CHECK(l4_store_hash(json,(DWORD)strlen(json),NULL,0,digest));BCRYPT_PKCS1_PADDING_INFO padding={BCRYPT_SHA256_ALGORITHM};DWORD n=0;CHECK(BCryptSignHash(key,&padding,digest,32,signature,384,&n,BCRYPT_PAD_PKCS1)==0 && n==384);}
static void document(const char* name,const char* size,const char* tail){sprintf_s(json,sizeof(json),"{\"schema\":1,\"kind\":\"frozen-supervisor-helper\",\"key_id\":\"%s\",\"version\":\"1.13.8\",\"manifest_sha256\":\"%s\",\"publisher_certificate_sha256\":\"%s\",\"helpers\":{\"x86\":{\"name\":\"%s\",\"size\":%s,\"sha256\":\"%s\"},\"x64\":{\"name\":\"l4rollback-x64.exe\",\"size\":321,\"sha256\":\"%s\"}}%s}",key_id,key_id,key_id,name,size,key_id,key_id,tail);sign_doc();}
static bool admit(const L4CatalogRelease* binding,const char* arch,SetupBootstrapReceipt* out){return setup_bootstrap_receipt_signed(json,(DWORD)strlen(json),signature,384,public_key,411,key_id,binding,arch,out);}
int wmain(void){
    memset(key_id,'1',64);key_id[64]=0;BCRYPT_ALG_HANDLE alg=NULL;DWORD n=0;CHECK(BCryptOpenAlgorithmProvider(&alg,BCRYPT_RSA_ALGORITHM,NULL,0)==0);CHECK(BCryptGenerateKeyPair(alg,&key,3072,0)==0);CHECK(BCryptFinalizeKeyPair(key,0)==0);CHECK(BCryptExportKey(key,NULL,BCRYPT_RSAPUBLIC_BLOB,public_key,411,&n,0)==0 && n==411);
    L4CatalogRelease release={0};strcpy_s(release.version,64,"1.13.8");memset(release.manifest_sha256,0x11,32);SetupBootstrapReceipt result={0};document("l4rollback-x86.exe","123","");
    CHECK(admit(&release,"x86",&result));CHECK(result.helper.size==123 && result.helper.sha256[0]==0x11 && !result.owner_trusted);CHECK(admit(&release,"x64",&result));CHECK(result.helper.size==321);CHECK(admit(NULL,"x64",&result));
    CHECK(!setup_bootstrap_receipt_trusted(json,(DWORD)strlen(json),signature,384,&release,"x86",&result));CHECK(!result.owner_trusted && !result.helper.size);
    signature[0]^=1;CHECK(!admit(&release,"x86",&result));signature[0]^=1;json[0]^=1;CHECK(!admit(&release,"x86",&result));json[0]^=1;
    CHECK(!admit(&release,"arm64",&result));release.manifest_sha256[0]^=1;CHECK(!admit(&release,"x86",&result));release.manifest_sha256[0]^=1;release.revoked=true;CHECK(!admit(&release,"x86",&result));release.revoked=false;strcpy_s(release.version,64,"1.13.9");CHECK(!admit(&release,"x86",&result));strcpy_s(release.version,64,"1.13.8");
    const char* names[]={"../l4rollback.exe","l4rollback-x64.exe","C:\\\\evil.exe","l4rollback-x86.exe:secret"};for(unsigned i=0;i<_countof(names);i++){document(names[i],"123","");CHECK(!admit(&release,"x86",&result));}
    const char* sizes[]={"0","4294967296","-1","true","1.5"};for(unsigned i=0;i<_countof(sizes);i++){document("l4rollback-x86.exe",sizes[i],"");CHECK(!admit(&release,"x64",&result));}
    document("l4rollback-x86.exe","123",",\"url\":\"http://localhost/\"");CHECK(!admit(&release,"x86",&result));document("l4rollback-x86.exe","123",",\"schema\":1");CHECK(!admit(&release,"x86",&result));document("l4rollback-x86.exe","123","");CHECK(!setup_bootstrap_receipt_signed(json,(DWORD)strlen(json),signature,383,public_key,411,key_id,&release,"x86",&result));
    SetupRecoveryReceipt* receipt=NULL;CHECK(!setup_recovery_receipt_load(NULL,"x86",&receipt));CHECK(!receipt);L4Journal j={0};j.lock=j.file=CreateEventW(NULL,TRUE,FALSE,NULL);CHECK(!setup_recovery_receipt_load(&j,"x86",&receipt));CHECK(GetLastError()==ERROR_ACCESS_DENIED);CloseHandle(j.lock);CHECK(!setup_recovery_receipt_helper(NULL));
    wchar_t temp[MAX_PATH],path[MAX_PATH],link[MAX_PATH],stream[MAX_PATH];CHECK(GetTempPathW(MAX_PATH,temp));swprintf_s(path,MAX_PATH,L"%lsbootstrap-receipt-%lu-%llu",temp,GetCurrentProcessId(),GetTickCount64());swprintf_s(link,MAX_PATH,L"%ls-link",path);swprintf_s(stream,MAX_PATH,L"%ls:unexpected",path);
    PSECURITY_DESCRIPTOR sd=NULL;CHECK(ConvertStringSecurityDescriptorToSecurityDescriptorW(L"O:BAD:P(A;;FA;;;SY)(A;;FA;;;BA)(A;;GRGX;;;BU)",SDDL_REVISION_1,&sd,NULL));const char bytes[]="immutable fixture";CHECK(write_new(path,NULL,bytes,sizeof(bytes),sd));CHECK(!write_new(path,NULL,"replace",8,sd));CHECK(GetLastError()==ERROR_FILE_EXISTS);
    HANDLE h=open(path);CHECK(h!=INVALID_HANDLE_VALUE);BYTE* data=NULL;DWORD size=0;CHECK(read(h,&data,&size,100));CHECK(size==sizeof(bytes) && !memcmp(data,bytes,size));free(data);L4RecoveryHelper expected={sizeof(bytes),{0}};CHECK(l4_store_hash(bytes,sizeof(bytes),NULL,0,expected.sha256));CHECK(hash(h,&expected));expected.sha256[0]^=1;CHECK(!hash(h,&expected));CloseHandle(h);
    CHECK(CreateHardLinkW(link,path,NULL));h=open(path);CHECK(h==INVALID_HANDLE_VALUE);CHECK(DeleteFileW(link));SECURITY_ATTRIBUTES sa={sizeof(sa),sd,FALSE};h=CreateFileW(stream,GENERIC_WRITE,0,&sa,CREATE_NEW,FILE_ATTRIBUTE_NORMAL,NULL);CHECK(h!=INVALID_HANDLE_VALUE);if(h!=INVALID_HANDLE_VALUE)CloseHandle(h);h=open(path);CHECK(h==INVALID_HANDLE_VALUE);CHECK(DeleteFileW(stream));
    /* Presence guard is not signature/health authority; partial first creation is
     * refused with a specific NOT_READY diagnostic, never silently adopted. */
    CHECK(!complete_paths(path,link,stream));CHECK(GetLastError()==ERROR_NOT_READY);CHECK(write_new(link,NULL,"invalid doc",12,sd));CHECK(!complete_paths(path,link,stream));CHECK(GetLastError()==ERROR_NOT_READY);CHECK(DeleteFileW(link));
    /* The low-level filesystem probe uses real protected temporary roots; this
     * is not a SYSTEM/root-authority substitution or positive signed installation. */
    CHECK(DeleteFileW(path));CHECK(CreateDirectoryW(path,NULL));wchar_t pf[MAX_PATH],pd[MAX_PATH],directory[MAX_PATH],helper_path[MAX_PATH],doc_path[MAX_PATH],sig_path[MAX_PATH];swprintf_s(pf,MAX_PATH,L"%ls\\PF",path);swprintf_s(pd,MAX_PATH,L"%ls\\PD",path);L4Journal probe={0};CHECK(l4_layout_from_roots(&probe.layout,pf,pd,L"1.13.8"));
    /* Only PF probe root is created, with owner/protected readonly policy. */
    SECURITY_ATTRIBUTES attr={sizeof(attr),sd,FALSE};CHECK(CreateDirectoryW(pf,&attr));L4FileFence parents={0};bool absent=false;CHECK(destination_state(&probe,&parents,&absent));CHECK(absent);l4_store_unpin(&parents);CHECK(paths(&probe,directory,helper_path,doc_path,sig_path));CHECK(GetFileAttributesW(directory)==INVALID_FILE_ATTRIBUTES);
    CHECK(CreateDirectoryW(directory,&attr));CHECK(!destination_state(&probe,&parents,&absent));CHECK(!absent && GetLastError()==ERROR_NOT_READY);l4_store_unpin(&parents);CHECK(GetFileAttributesW(helper_path)==INVALID_FILE_ATTRIBUTES);CHECK(write_new(helper_path,NULL,bytes,sizeof(bytes),sd));CHECK(!destination_state(&probe,&parents,&absent));CHECK(GetLastError()==ERROR_NOT_READY);l4_store_unpin(&parents);
    document("l4rollback-x86.exe","123","");CHECK(admit(&release,"x86",&result));SetupBootstrapReceipt identical=result;CHECK(same_identity(&result,&identical));identical.helper.sha256[0]^=1;CHECK(!same_identity(&result,&identical));identical=result;identical.publisher[0]^=1;CHECK(!same_identity(&result,&identical));
    CHECK(DeleteFileW(helper_path));CHECK(RemoveDirectoryW(directory));PSECURITY_DESCRIPTOR unsafe=NULL;CHECK(ConvertStringSecurityDescriptorToSecurityDescriptorW(L"O:BAD:P(A;;FA;;;SY)(A;;FA;;;BA)(A;;FA;;;BU)",SDDL_REVISION_1,&unsafe,NULL));CHECK(SetFileSecurityW(pf,DACL_SECURITY_INFORMATION,unsafe));CHECK(!destination_state(&probe,&parents,&absent));CHECK(!absent && GetLastError()==ERROR_ACCESS_DENIED);l4_store_unpin(&parents);CHECK(SetFileSecurityW(pf,DACL_SECURITY_INFORMATION,sd));LocalFree(unsafe);CHECK(RemoveDirectoryW(pf));CHECK(RemoveDirectoryW(path));LocalFree(sd);BCryptDestroyKey(key);BCryptCloseAlgorithmProvider(alg,0);printf("bootstrap signed receipt / immutable file guards: %u checks, %u failures\n",checks,failures);return failures?1:0;
}
/* Authenticode is outside this file-only fixture; any accidental entry fails. */
bool setup_signed_executable_policy(HANDLE h,const wchar_t* p,const BYTE publisher[32],SetupAdmissionPolicy policy){(void)h;(void)p;(void)publisher;(void)policy;++failures;return fail(ERROR_CALL_NOT_IMPLEMENTED);}
