/* Actual compiled executor and random-port/clock composition. All admission,
 * journals, SCM, app/IPC and recovery adapters below are modeled. Actual native
 * process/journal/108 boundaries are verified by separate focused fixtures;
 * this fixture is not runtime signed acceptance or permission to enable RPC. */
#include "../src/remote_executor.h"
#include "../../l4common/journal_internal.h"
#include <stdio.h>
#include <string.h>
static unsigned assertions,failures,calls,inject,mutations,restores,probe_count,barrier_count,opened,closed,candidates,captures;static bool switched_window2,done,cleared;static unsigned phases[4];static bool config_new[12];
static bool sealed_failure,settling_without_proof,deny_restore,force_local;static unsigned required_count,first_mutation_call;static bool spend_budget;static ULONGLONG elapsed_ms;static ULONGLONG fixture_ticks(void){return GetTickCount64()+elapsed_ms;}static VOID WINAPI fixture_utc(LPFILETIME out){GetSystemTimeAsFileTime(out);ULONGLONG value=((ULONGLONG)out->dwHighDateTime<<32)|out->dwLowDateTime;value+=elapsed_ms*10000;out->dwLowDateTime=(DWORD)value;out->dwHighDateTime=(DWORD)(value>>32);}
#define CHECK(x) do{assertions++;if(!(x)){failures++;printf("FAIL executor line%u %s error%lu\n",__LINE__,#x,GetLastError());}}while(0)
static bool gate(void){calls++;if(calls==inject){SetLastError(ERROR_ACCESS_DENIED);return false;}return true;}
#define GetTickCount64 fixture_ticks
#define GetSystemTimeAsFileTime fixture_utc
#include "../src/remote_executor.c"
#undef GetTickCount64
#undef GetSystemTimeAsFileTime
static L4BootstrapPlan old_plan;static L4Layout target_layout;static L4ServiceSwitch switches[4];static L4AccessActors actors;static L4CommunicationPlan link_plan;static L4WorkerAdmission admitted;static L4UpdateState state;static ULONGLONG refs[12];static unsigned hops=1;static DWORD pending;static BYTE plan_hash[32];
unsigned setup_operation_hops(const SetupOperationPlan* p){CHECK(p);return hops;}
bool l4_worker_recheck(L4Journal* j,L4WorkerAdmission* out){CHECK(j && !state.window);*out=admitted;return gate();}
bool l4_worker_recheck_active(L4Journal* j,const L4UpdateState* expected,L4WorkerAdmission* out){CHECK(j && expected->window && expected->window==state.window && expected->generation==state.generation);*out=admitted;return gate();}
bool setup_operation_binding(const SetupOperationPlan* p,L4Journal* j,ULONGLONG sequence){CHECK(p && j && sequence==64);return gate();}
bool setup_operation_verify_images(const SetupOperationPlan* p){CHECK(p);return gate();}
bool setup_installed_source_open(L4Journal* j,SetupInstalledSource** out){CHECK(j && !state.window);*out=(SetupInstalledSource*)1;return gate();}
bool setup_installed_source_verify(SetupInstalledSource* s){CHECK(s && !state.window);return gate();}
bool setup_installed_source_owned_by(const SetupInstalledSource* s,const L4Journal* j){CHECK(s && j);return gate();}
const L4BootstrapPlan* setup_installed_source_plan(const SetupInstalledSource* s){CHECK(s && !state.window);return &old_plan;}
const L4AccessActors* setup_installed_source_actors(const SetupInstalledSource* s){CHECK(s && !state.window);return &actors;}
void setup_installed_source_close(SetupInstalledSource* s){(void)s;}
const SetupManifest* setup_operation_target(const SetupOperationPlan* p,unsigned hop){CHECK(p && !hop);return (SetupManifest*)1;}
const L4Layout* setup_manifest_layout(const SetupManifest* p){CHECK(p);return &target_layout;}
const L4ServiceSwitch* setup_operation_switch(const SetupOperationPlan* p,unsigned hop,unsigned i){CHECK(p && !hop && i<4);return &switches[i];}
ULONGLONG setup_operation_switch_reference(const SetupOperationPlan* p,unsigned hop,unsigned i){CHECK(p && !hop && i<4);return 10+i;}
const ULONGLONG* setup_operation_configs(const SetupOperationPlan* p,unsigned* n){CHECK(p);*n=12;return refs;}
bool l4_proxy_signal_source(const wchar_t* command,WORD* http,WORD* mqtt,char thumb[64]){CHECK(command && *command);*http=18443;*mqtt=18883;thumb[0]=0;return gate();}
static bool model_probe(const L4BootstrapPlan* p,unsigned i,DWORD ms,void* context){(void)context;CHECK(p && i<4 && ms);if(p==&old_plan || !wcscmp(p->commands[i],old_plan.commands[i])){CHECK(phases[i]==3);if(i==1)CHECK(phases[0]==3 && !config_new[1] && !config_new[2]);}else{CHECK(phases[i]==4);if(i==0)CHECK(phases[1]==3);if(i==1)CHECK(phases[0]==4 && config_new[1] && config_new[2]);if(i==2)CHECK(switched_window2);}if(spend_budget){if(i==1){CHECK(ms<=51000 && ms>=50000);elapsed_ms+=50000;}else elapsed_ms+=60000;}probe_count++;return gate();}
static bool model_barrier(const L4BootstrapPlan* p,DWORD ms,void* context){(void)context;CHECK(p && ms && phases[0]==4 && phases[1]==4 && phases[2]==3 && !switched_window2);if(spend_budget)elapsed_ms+=60000;barrier_count++;return gate();}
bool setup_readiness_checks(L4Readiness* options,const DWORD budgets[4],DWORD b,L4BootstrapChecks* out){CHECK(options->proxy_port==18443 && options->broker_port==1883 && budgets[1]==300000 && b==60000);memset(out,0,sizeof(*out));out->probe=model_probe;out->barrier=model_barrier;memcpy(out->service_ms,budgets,sizeof(out->service_ms));out->barrier_ms=b;return gate();}
bool l4_communication_plan_open(const L4Layout* l,const wchar_t* id,L4CommunicationPin** out){CHECK(l && id);*out=(L4CommunicationPin*)1;return gate();}
bool l4_communication_plan_verify_journal(L4Journal* j,const L4CommunicationPin* p){CHECK(j && p);return gate();}
const L4CommunicationPlan* l4_communication_pinned_plan(const L4CommunicationPin* p){CHECK(p);return &link_plan;}
void l4_communication_plan_close(L4CommunicationPin* p){(void)p;}
bool l4_update_state_read(const L4Layout* l,L4UpdateState* out){CHECK(l);*out=state;return gate();}
bool setup_update_worker_capture_stop(L4Journal* j,ULONGLONG seq,const L4AccessActors* a,const L4BootstrapChecks* c,DWORD ms,SetupStopGate** out){CHECK(j && seq==64 && a && c && ms && !state.window);captures++;*out=(SetupStopGate*)1;return gate();}
void setup_update_stop_gate_free(SetupStopGate* p){(void)p;}
bool setup_update_watch_ready(L4Journal* j,SetupStopGate* p,ULONGLONG deadline,DWORD ms){CHECK(j && p && deadline==link_plan.deadline_utc && ms && !state.window);return gate();}
bool setup_update_confirm_stop(L4Journal* j,SetupStopGate* p,const L4AccessActors* a,const L4BootstrapChecks* c,DWORD ms){CHECK(j && p && a && c && ms && state.window==1);return gate();}
bool setup_remote_completion_prepare(L4Journal* j,SetupInstalledSource* source,const SetupOperationPlan* op,SetupRemoteCompletion** out){CHECK(j && source && op && !state.window);*out=(SetupRemoteCompletion*)1;return gate();}
void setup_remote_completion_free(SetupRemoteCompletion* p){(void)p;}
bool setup_remote_completion_settling(const SetupRemoteCompletion* p){CHECK(p);return sealed_failure || settling_without_proof;}
bool setup_remote_restore_prepare(L4Journal* j,SetupInstalledSource* source,const SetupOperationPlan* op,SetupRemoteRestore** out){CHECK(j && source && op && !state.window);*out=(SetupRemoteRestore*)1;return gate();}
void setup_remote_restore_free(SetupRemoteRestore* p){(void)p;}
bool setup_update_candidate_probe(L4Journal* j,ULONGLONG seq,unsigned hop,WORD http,WORD mqtt,DWORD ms){CHECK(j && seq==64 && !hop && http>=49152 && mqtt>=49152 && http!=mqtt && ms==180000 && !state.window && !mutations);candidates++;return gate();}
bool l4_update_state_publish(L4Journal* j,ULONGLONG seq,ULONGLONG generation,DWORD window,ULONGLONG deadline){CHECK(j && seq==64 && generation==state.generation && window>=1 && window<=2);if(window==2){CHECK(done && phases[0]==4 && phases[1]==4 && deadline==admitted.deadline_utc-300000000ull);switched_window2=true;}if(!gate())return false;state.window=window;state.generation++;state.plan_sequence=seq;state.deadline_utc=deadline;return true;}
bool setup_remote_service_open(L4Journal* j,ULONGLONG ref,const L4ServiceSwitch* change,const L4UpdateState* expected,DWORD ms,SetupRemoteService** out){CHECK(j && ref>=10 && ref<14 && change==&switches[ref-10] && expected->window==1 && ms && !mutations);if(!gate())return false;*out=(SetupRemoteService*)(ULONG_PTR)(100+ref-10);opened++;return true;}
void setup_remote_service_close(SetupRemoteService* p){if(p)closed++;}
bool setup_remote_service_rebind_state(SetupRemoteService* p,const L4UpdateState* expected,ULONGLONG deadline){CHECK(p && expected->window==2 && deadline==admitted.deadline_utc);return gate();}
bool setup_service_transaction_open(L4Journal* j,const SetupOperationPlan* op,SetupRemoteService* sv[4],SetupServiceTransaction** out){CHECK(j && op && sv && opened==4);*out=(SetupServiceTransaction*)1;return gate();}
void setup_service_transaction_close(SetupServiceTransaction* p){(void)p;}
bool setup_service_transaction_execute(SetupServiceTransaction* t,unsigned i,SetupServiceAction action,const L4UpdateState* expected,DWORD ms){CHECK(t && i<4 && action>=1 && action<=3 && expected->window==state.window && ms);if(i>=2)CHECK(switched_window2 && done);if(i==1)CHECK(probe_count>=1);if(!first_mutation_call)first_mutation_call=calls+1;if(!gate()){pending=100;return false;}if(spend_budget){if(i==1 && action==3){CHECK(ms>=299000);elapsed_ms+=249000;}else elapsed_ms+=60000;}phases[i]=action==1?1:action==2?2:4;mutations++;return true;}
bool l4_config_apply(L4Journal* j,ULONGLONG ref){CHECK(j && ref>=20 && ref<32);unsigned index=(unsigned)(ref-20);if(index==0)CHECK(phases[3]==1);if(index==1 || index==2)CHECK(phases[1]==1);if(index>=3)CHECK(phases[2]==4 && phases[3]==4);if(!gate()){pending=21;return false;}config_new[index]=true;return true;}
bool l4_config_verify(L4Journal* j,ULONGLONG ref,bool candidate){CHECK(j && ref>=20 && ref<32);return config_new[ref-20]==candidate;}
bool l4_config_rollback(L4Journal* j,ULONGLONG ref){CHECK(j && ref>=20 && ref<32);unsigned i=(unsigned)(ref-20);if(i==0)CHECK(phases[3]==1 || phases[3]==3);if(i==1 || i==2)CHECK(phases[1]==1 || phases[1]==3);if(!gate())return false;config_new[i]=false;return true;}
bool l4_communication_decision_open(const L4Layout* l,const wchar_t* id,DWORD ms,L4CommunicationDecision** out){CHECK(l && id && ms);*out=(L4CommunicationDecision*)1;return gate();}
bool l4_communication_decision_read(L4CommunicationDecision* p,L4CommunicationPhase* phase,DWORD* code){CHECK(p);*phase=done?L4_COMM_DEC_COMMITTED:L4_COMM_DEC_WAIT;*code=0;return gate();}
bool l4_communication_decision_finish(L4CommunicationDecision* p,L4CommunicationPhase phase,DWORD code,ULONGLONG now){CHECK(p && phase==L4_COMM_DEC_COMMITTED && !code && now && barrier_count);if(!gate())return false;done=true;return true;}
void l4_communication_decision_close(L4CommunicationDecision* p){(void)p;}
bool l4_communication_native_budget_valid(const L4CommunicationBudget* b){CHECK(b && b->total_ms==1050000);return true;}
bool setup_service_transaction_pending(SetupServiceTransaction* t,DWORD* kind){CHECK(t);*kind=pending;return gate();}
bool setup_service_transaction_abandon(SetupServiceTransaction* t,const L4UpdateState* expected,DWORD ms){CHECK(t && expected->window && ms && pending==100);if(deny_restore)return fail(ERROR_RECOVERY_FAILURE);pending=0;return gate();}
bool setup_service_transaction_abandon_config(SetupServiceTransaction* t,const L4UpdateState* expected,DWORD ms){CHECK(t && expected->window && ms && pending==21);pending=0;return gate();}
bool setup_remote_service_observe(SetupRemoteService* p,SetupRemoteServiceObservation* out){unsigned i=(unsigned)(ULONG_PTR)p-100;CHECK(i<4);memset(out,0,sizeof(*out));out->phase=(SetupRemoteServicePhase)phases[i];out->state=state;return gate();}
bool setup_service_transaction_restore(SetupServiceTransaction* t,unsigned i,SetupServiceRestore action,const L4UpdateState* expected,DWORD ms){CHECK(t && i<4 && expected->window && ms && !pending);if(!gate())return false;if(action==4)CHECK(phases[i]==3);else phases[i]=action==1?1:action==2?1:3;restores++;return true;}
bool setup_remote_completion_finish(SetupRemoteCompletion* p,L4Journal* j,const SetupOperationPlan* op,SetupServiceTransaction* t,SetupRemoteService* sv[4],DWORD ms,L4RemoteOutcome* out){CHECK(p && j && op && t && sv && ms && ms<=600000 && state.window==2);for(unsigned i=0;i<4;i++)CHECK(phases[i]==4);for(unsigned i=0;i<12;i++)CHECK(config_new[i]);if(spend_budget){CHECK(ms==600000);elapsed_ms+=540000;}if(sealed_failure || settling_without_proof)return fail(ERROR_WRITE_FAULT);if(!gate())return false;out->result.result=L4_REMOTE_OUTCOME_SUCCESS;cleared=true;state.window=0;return true;}
bool setup_remote_restore_finish(SetupRemoteRestore* p,L4Journal* j,const SetupOperationPlan* op,SetupServiceTransaction* t,SetupRemoteService* sv[4],DWORD error,DWORD ms,L4RemoteOutcome* out){CHECK(p && j && op && t && sv && error && ms && state.window);for(unsigned i=0;i<4;i++)CHECK(phases[i]==3);for(unsigned i=0;i<12;i++)CHECK(!config_new[i]);if(!gate())return false;out->result.result=L4_REMOTE_OUTCOME_RESTORED;cleared=true;state.window=0;return true;}
bool setup_remote_outcome_append_bound(L4Journal* j,const SetupOperationPlan* p,const L4RemoteOutcome* expected,ULONGLONG ref,const BYTE hash[32],L4RemoteOutcome* out){CHECK(j && p && expected->result.result==L4_REMOTE_OUTCOME_RECOVERY_REQUIRED && !ref && !hash && state.window);required_count++;*out=*expected;return true;}
bool setup_acceptance_forcepoint(L4Journal* j,const SetupOperationPlan* p,bool* forced){CHECK(j && p && forced && state.window==2 && !cleared);for(unsigned i=0;i<4;i++)CHECK(phases[i]==4);for(unsigned i=0;i<12;i++)CHECK(config_new[i]);if(!gate())return false;*forced=force_local;return true;}
bool l4_journal_replay(L4Journal* j,L4JournalVisitor visitor,void* context){CHECK(j && visitor && context);return !sealed_failure || visitor(102,200,NULL,0,context);}
static void reset(L4Journal* j){sealed_failure=settling_without_proof=deny_restore=force_local=false;required_count=first_mutation_call=0;spend_budget=false;elapsed_ms=0;calls=inject=mutations=restores=probe_count=barrier_count=opened=closed=candidates=captures=pending=0;done=switched_window2=cleared=false;hops=1;memset(&state,0,sizeof(state));memset(&admitted,0,sizeof(admitted));memset(&old_plan,0,sizeof(old_plan));memset(&link_plan,0,sizeof(link_plan));memset(config_new,0,sizeof(config_new));strcpy_s(state.owner,40,"17730000-0000-4000-8000-000000000001");wcscpy_s(j->directory,MAX_PATH,L"C:\\fixture\\17730000-0000-4000-8000-000000000001");admitted.sequence=64;admitted.helper.size=123;admitted.helper.sha256[0]=1;SetupRemoteWorkerPolicy policy;CHECK(setup_remote_policy_at(utc(),&policy));admitted.deadline_utc=policy.supervisor_deadline_utc;link_plan.armed_utc=policy.armed_utc;link_plan.deadline_utc=policy.communication_deadline_utc;link_plan.sequence=64;link_plan.generation=1;link_plan.worker_pid=GetCurrentProcessId();FILETIME e,k,u;CHECK(GetProcessTimes(GetCurrentProcess(),&link_plan.worker_created,&e,&k,&u));link_plan.budget=policy.communication;memcpy(link_plan.operation_sha256,plan_hash,32);for(unsigned i=0;i<4;i++){phases[i]=3;swprintf_s(old_plan.services[i],32,L"service%u",i);swprintf_s(old_plan.commands[i],2048,L"old-command%u",i);memset(&switches[i],0,sizeof(switches[i]));wcscpy_s(switches[i].service,32,old_plan.services[i]);wcscpy_s(switches[i].before.image_path,2048,old_plan.commands[i]);swprintf_s(switches[i].after,2048,L"new-command%u",i);}for(unsigned i=0;i<12;i++)refs[i]=20+i;}
int main(void){L4Journal j={0};SetupOperationPlan* op=(SetupOperationPlan*)1;const SetupWorkerEngine* engine=setup_remote_executor_engine();CHECK(engine && engine->preflight && engine->execute);reset(&j);CHECK(engine->preflight(&j,op,&admitted,&admitted.helper));CHECK(!captures && !mutations && !candidates && !state.window);reset(&j);L4Journal* owner=&j;CHECK(engine->execute(&owner,op,&admitted,&admitted.helper)==0);CHECK(cleared && mutations==12 && opened==4 && closed==4 && candidates==1 && captures==1 && barrier_count==1 && probe_count==4);unsigned total=calls,first_action=first_mutation_call;reset(&j);spend_budget=true;owner=&j;CHECK(engine->execute(&owner,op,&admitted,&admitted.helper)==0);CHECK(cleared && elapsed_ms==1739000);
 for(unsigned at=1;at<=total;at++){reset(&j);inject=at;owner=&j;DWORD rc=engine->execute(&owner,op,&admitted,&admitted.helper);CHECK(rc || (cleared && mutations==12));CHECK(opened==closed);if(!state.window)CHECK(!mutations || restores || !rc);}
 reset(&j);deny_restore=true;inject=first_action;owner=&j;CHECK(engine->execute(&owner,op,&admitted,&admitted.helper)!=0);CHECK(state.window==1 && !restores && required_count==1 && !cleared);reset(&j);sealed_failure=true;owner=&j;CHECK(engine->execute(&owner,op,&admitted,&admitted.helper)!=0);CHECK(state.window==2 && !restores && !required_count && !cleared);reset(&j);settling_without_proof=true;owner=&j;CHECK(engine->execute(&owner,op,&admitted,&admitted.helper)!=0);CHECK(state.window==2 && !restores && required_count==1 && !cleared);reset(&j);force_local=true;owner=&j;CHECK(engine->execute(&owner,op,&admitted,&admitted.helper)==ERROR_CANCELLED);CHECK(cleared && restores && !required_count && !state.window);reset(&j);hops=2;owner=&j;CHECK(engine->execute(&owner,op,&admitted,&admitted.helper)==ERROR_NOT_SUPPORTED && !mutations && !candidates && !opened);reset(&j);admitted.helper.sha256[0]^=1;L4RecoveryHelper wrong=admitted.helper;wrong.sha256[0]^=1;owner=&j;CHECK(engine->execute(&owner,op,&admitted,&wrong)!=0 && !mutations && !opened);printf("Remote executor: %u passed, %u failed; orchestration actual, authority/SCM/IPC/guards modeled\n",assertions-failures,failures);return failures?1:0;}
