//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tb_Accounts
{
    public tb_Accounts()
    {
        this.tb_Operations = new HashSet<tb_Operations>();
        this.tb_Operations1 = new HashSet<tb_Operations>();
    }

    public int Id { get; set; }
    public int CurrencyTypeId { get; set; }
    public int ClientId { get; set; }
    public int AccountTypeId { get; set; }
    public decimal Balance { get; set; }

    public virtual tb_Clients tb_Clients { get; set; }
    public virtual ICollection<tb_Operations> tb_Operations { get; set; }
    public virtual ICollection<tb_Operations> tb_Operations1 { get; set; }
}

public partial class tb_Actions
{
    public tb_Actions()
    {
        this.tb_Emissions = new HashSet<tb_Emissions>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public System.Guid BannerImage { get; set; }
    public byte Percent { get; set; }

    public virtual ICollection<tb_Emissions> tb_Emissions { get; set; }
}

public partial class tb_BillAllowances
{
    public int Id { get; set; }
    public int EmissionId { get; set; }
    public decimal MinBillSum { get; set; }
    public byte Percent { get; set; }

    public virtual tb_Emissions tb_Emissions { get; set; }
}

public partial class tb_BillProfits
{
    public int Id { get; set; }
    public int BillId { get; set; }
    public System.DateTime ProfitDateTime { get; set; }
    public decimal Sum { get; set; }

    public virtual tb_Bills tb_Bills { get; set; }
}

public partial class tb_Bills
{
    public tb_Bills()
    {
        this.tb_BillProfits = new HashSet<tb_BillProfits>();
        this.tb_BuyoutRequest = new HashSet<tb_BuyoutRequest>();
        this.tb_Operations = new HashSet<tb_Operations>();
        this.tb_Payments = new HashSet<tb_Payments>();
    }

    public int Id { get; set; }
    public int EmissionId { get; set; }
    public int InvestorId { get; set; }
    public int Number { get; set; }
    public decimal Nominal { get; set; }
    public int StatusId { get; set; }
    public System.DateTime StatusDateTime { get; set; }
    public int StatusUserId { get; set; }
    public string StatusComment { get; set; }
    public Nullable<int> ReferrerId { get; set; }
    public bool ParticipationInAction { get; set; }
    public Nullable<System.Guid> DocumentAttachment { get; set; }
    public int LocationId { get; set; }
    public string Code { get; set; }
    public Nullable<System.DateTime> ActivateDateTime { get; set; }
    public Nullable<System.DateTime> KillDateTime { get; set; }

    public virtual ICollection<tb_BillProfits> tb_BillProfits { get; set; }
    public virtual tb_Emissions tb_Emissions { get; set; }
    public virtual tb_Investors tb_Investors { get; set; }
    public virtual tb_Locations tb_Locations { get; set; }
    public virtual ICollection<tb_BuyoutRequest> tb_BuyoutRequest { get; set; }
    public virtual ICollection<tb_Operations> tb_Operations { get; set; }
    public virtual ICollection<tb_Payments> tb_Payments { get; set; }
}

public partial class tb_Blogs
{
    public int Id { get; set; }
    public System.DateTime CreateDateTime { get; set; }
    public string Header { get; set; }
    public string Text { get; set; }
    public int StatusId { get; set; }
    public System.DateTime StatusDateTime { get; set; }
    public int StatusUserId { get; set; }
    public string StatusComment { get; set; }
    public int ClientId { get; set; }

    public virtual tb_Clients tb_Clients { get; set; }
}

public partial class tb_BuyoutRequest
{
    public int Id { get; set; }
    public int BillId { get; set; }
    public decimal BuyoutSumm { get; set; }
    public int StatusId { get; set; }
    public System.DateTime StatusDateTime { get; set; }
    public int StatusUserId { get; set; }
    public string StatusComment { get; set; }

    public virtual tb_Bills tb_Bills { get; set; }
}

public partial class tb_ClientDocuments
{
    public int Id { get; set; }
    public int ClientId { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public int ClientDocumentTypeId { get; set; }
    public Nullable<System.Guid> Image { get; set; }

    public virtual tb_Clients tb_Clients { get; set; }
}

public partial class tb_Clients
{
    public tb_Clients()
    {
        this.tb_Accounts = new HashSet<tb_Accounts>();
        this.tb_Blogs = new HashSet<tb_Blogs>();
        this.tb_ClientDocuments = new HashSet<tb_ClientDocuments>();
        this.tb_ExternalAccounts = new HashSet<tb_ExternalAccounts>();
        this.tb_PayIn = new HashSet<tb_PayIn>();
        this.tb_Users = new HashSet<tb_Users>();
    }

    public int Id { get; set; }
    public string Description { get; set; }
    public int ClientTypeId { get; set; }
    public bool IsJuridical { get; set; }
    public int StatusId { get; set; }
    public System.DateTime StatusDateTime { get; set; }
    public int StatusUserId { get; set; }
    public string StatusComment { get; set; }

    public virtual ICollection<tb_Accounts> tb_Accounts { get; set; }
    public virtual ICollection<tb_Blogs> tb_Blogs { get; set; }
    public virtual ICollection<tb_ClientDocuments> tb_ClientDocuments { get; set; }
    public virtual ts_ClientTypes ts_ClientTypes { get; set; }
    public virtual tb_Emissioners tb_Emissioners { get; set; }
    public virtual ICollection<tb_ExternalAccounts> tb_ExternalAccounts { get; set; }
    public virtual tb_Investors tb_Investors { get; set; }
    public virtual tb_Organizations tb_Organizations { get; set; }
    public virtual ICollection<tb_PayIn> tb_PayIn { get; set; }
    public virtual ICollection<tb_Users> tb_Users { get; set; }
}

public partial class tb_Counters
{
    public int Id { get; set; }
    public string NameObj { get; set; }
    public int NumValue { get; set; }
    public Nullable<int> NumYear { get; set; }
    public string Description { get; set; }
}

public partial class tb_EBS_KioskEmissions
{
    public int Id { get; set; }
    public int KioskId { get; set; }
    public int EmissionId { get; set; }
}

public partial class tb_EmissionAddPercent
{
    public int Id { get; set; }
    public int EmissionId { get; set; }
    public decimal MinSumm { get; set; }
    public decimal MaxSumm { get; set; }
    public decimal AddPercent { get; set; }

    public virtual tb_Emissions tb_Emissions { get; set; }
}

public partial class tb_EmissionDocs
{
    public int Id { get; set; }
    public int EmissionId { get; set; }
    public string DocumentName { get; set; }
    public System.Guid FileId { get; set; }

    public virtual tb_Emissions tb_Emissions { get; set; }
}

public partial class tb_Emissioners
{
    public tb_Emissioners()
    {
        this.tb_Emissions = new HashSet<tb_Emissions>();
    }

    public int Id { get; set; }
    public string Domen { get; set; }
    public string DigitalSign { get; set; }

    public virtual tb_Clients tb_Clients { get; set; }
    public virtual ICollection<tb_Emissions> tb_Emissions { get; set; }
}

public partial class tb_EmissionRequest
{
    public long Id { get; set; }
    public int EmissionId { get; set; }
    public Nullable<int> EconomicState { get; set; }
    public Nullable<int> LegalState { get; set; }
    public System.DateTime Data { get; set; }
    public string Description { get; set; }

    public virtual tb_Emissions tb_Emissions { get; set; }
}

public partial class tb_Emissions
{
    public tb_Emissions()
    {
        this.tb_BillAllowances = new HashSet<tb_BillAllowances>();
        this.tb_Bills = new HashSet<tb_Bills>();
        this.tb_EmissionAddPercent = new HashSet<tb_EmissionAddPercent>();
        this.tb_EmissionDocs = new HashSet<tb_EmissionDocs>();
        this.tb_EmissionRequest = new HashSet<tb_EmissionRequest>();
        this.tb_EmissionYield = new HashSet<tb_EmissionYield>();
        this.tb_ReferrerReward = new HashSet<tb_ReferrerReward>();
    }

    public int Id { get; set; }
    public int EmissionerId { get; set; }
    public byte AheadOfTimePercent { get; set; }
    public decimal Limit { get; set; }
    public decimal SaleSum { get; set; }
    public decimal MinBillSum { get; set; }
    public decimal MaxBillSum { get; set; }
    public int StatusId { get; set; }
    public System.DateTime StatusDateTime { get; set; }
    public int StatusUserId { get; set; }
    public string StatusComment { get; set; }
    public string Comment { get; set; }
    public bool TurnOnReferrers { get; set; }
    public byte BillPeriodInMonths { get; set; }
    public Nullable<System.Guid> Image { get; set; }
    public Nullable<int> ActionId { get; set; }

    public virtual tb_Actions tb_Actions { get; set; }
    public virtual ICollection<tb_BillAllowances> tb_BillAllowances { get; set; }
    public virtual ICollection<tb_Bills> tb_Bills { get; set; }
    public virtual ICollection<tb_EmissionAddPercent> tb_EmissionAddPercent { get; set; }
    public virtual ICollection<tb_EmissionDocs> tb_EmissionDocs { get; set; }
    public virtual tb_Emissioners tb_Emissioners { get; set; }
    public virtual ICollection<tb_EmissionRequest> tb_EmissionRequest { get; set; }
    public virtual ICollection<tb_EmissionYield> tb_EmissionYield { get; set; }
    public virtual ICollection<tb_ReferrerReward> tb_ReferrerReward { get; set; }
}

public partial class tb_EmissionYield
{
    public int Id { get; set; }
    public int EmissionId { get; set; }
    public byte MonthNumber { get; set; }
    public byte Percent { get; set; }

    public virtual tb_Emissions tb_Emissions { get; set; }
}

public partial class tb_Experts
{
    public int Id { get; set; }
}

public partial class tb_ExternalAccounts
{
    public tb_ExternalAccounts()
    {
        this.tb_Operations = new HashSet<tb_Operations>();
    }

    public int Id { get; set; }
    public int ClientId { get; set; }
    public int IsCurrent { get; set; }
    public bool IsActive { get; set; }
    public int ExternalAccountTypeId { get; set; }
    public int CurrencyTypeId { get; set; }
    public string AccountNumber { get; set; }
    public string Bank { get; set; }
    public string BIK { get; set; }
    public string KorAccountNumber { get; set; }
    public string SWIFTCode { get; set; }
    public string CorrespondentBank { get; set; }
    public string SWIFTCorrespondentBank { get; set; }
    public string CorrespondentAccount { get; set; }

    public virtual tb_Clients tb_Clients { get; set; }
    public virtual ICollection<tb_Operations> tb_Operations { get; set; }
}

public partial class tb_Investors
{
    public tb_Investors()
    {
        this.tb_Bills = new HashSet<tb_Bills>();
    }

    public int Id { get; set; }

    public virtual ICollection<tb_Bills> tb_Bills { get; set; }
    public virtual tb_Clients tb_Clients { get; set; }
}

public partial class tb_Locations
{
    public tb_Locations()
    {
        this.tb_Bills = new HashSet<tb_Bills>();
    }

    public int Id { get; set; }
    public string Address { get; set; }
    public string Description { get; set; }
    public string CoordX { get; set; }
    public string CoordY { get; set; }
    public int LocationTypeId { get; set; }

    public virtual ICollection<tb_Bills> tb_Bills { get; set; }
}

public partial class tb_News
{
    public long Id { get; set; }
    public System.DateTime Data { get; set; }
    public string Title { get; set; }
    public string Desscription { get; set; }
}

public partial class tb_Operations
{
    public int Id { get; set; }
    public int OperationSourceId { get; set; }
    public int OperationSourceTypeId { get; set; }
    public Nullable<int> SourceAccountId { get; set; }
    public Nullable<int> DestinationAccountId { get; set; }
    public Nullable<int> ExternalAccountId { get; set; }
    public System.DateTime DateTime { get; set; }
    public decimal Sum { get; set; }
    public int OperationTypeId { get; set; }
    public int StatusId { get; set; }
    public System.DateTime StatusDateTime { get; set; }
    public int StatusUserId { get; set; }
    public string StatusComment { get; set; }
    public string Description { get; set; }

    public virtual tb_Accounts tb_Accounts { get; set; }
    public virtual tb_Accounts tb_Accounts1 { get; set; }
    public virtual tb_Bills tb_Bills { get; set; }
    public virtual tb_ExternalAccounts tb_ExternalAccounts { get; set; }
    public virtual tb_Payments tb_Payments { get; set; }
    public virtual ts_OperationSourceTypes ts_OperationSourceTypes { get; set; }
    public virtual ts_OperationTypes ts_OperationTypes { get; set; }
}

public partial class tb_Organizations
{
    public int Id { get; set; }
    public int PropertyCategoryId { get; set; }
    public string Name { get; set; }
    public string INN { get; set; }
    public string BIK { get; set; }
    public string JurAddress { get; set; }
    public string FactAddress { get; set; }
    public string PostAddress { get; set; }
    public string Site { get; set; }
    public string Description { get; set; }
    public string DirectorLastName { get; set; }
    public string DirectorFirstName { get; set; }
    public string DirectorSurName { get; set; }
    public string Phone { get; set; }
    public string Email { get; set; }
    public string OGRN { get; set; }
    public string Bank { get; set; }
    public string Ras { get; set; }
    public Nullable<System.Guid> LogoImage { get; set; }

    public virtual tb_Clients tb_Clients { get; set; }
}

public partial class tb_PayIn
{
    public long Id { get; set; }
    public int ClientId { get; set; }
    public decimal Summa { get; set; }
    public bool IsPayd { get; set; }

    public virtual tb_Clients tb_Clients { get; set; }
}

public partial class tb_Payments
{
    public tb_Payments()
    {
        this.tb_Operations = new HashSet<tb_Operations>();
    }

    public int Id { get; set; }
    public int BillId { get; set; }
    public System.DateTime DateTime { get; set; }
    public decimal Sum { get; set; }
    public int PaymentTypeId { get; set; }

    public virtual tb_Bills tb_Bills { get; set; }
    public virtual ICollection<tb_Operations> tb_Operations { get; set; }
}

public partial class tb_ReferrerReward
{
    public long Id { get; set; }
    public Nullable<int> EmissionId { get; set; }
    public decimal BonusFix { get; set; }
    public decimal BonusPercent { get; set; }

    public virtual tb_Emissions tb_Emissions { get; set; }
}

public partial class tb_Referrers
{
    public int Id { get; set; }
}

public partial class tb_RolesRights
{
    public int Id { get; set; }
    public int RoleId { get; set; }
    public int RightId { get; set; }

    public virtual ts_Rights ts_Rights { get; set; }
    public virtual ts_Roles ts_Roles { get; set; }
}

public partial class tb_Settings
{
    public int Id { get; set; }
    public string SettingsName { get; set; }
    public string SettingsValueString { get; set; }
    public Nullable<decimal> SettingsValueDecimal { get; set; }
}

public partial class tb_Shifts
{
    public int Id { get; set; }
    public System.DateTime OpenDateTime { get; set; }
    public Nullable<System.DateTime> CloseDateTime { get; set; }
    public int UserId { get; set; }
    public Nullable<int> KioskId { get; set; }
    public string InkassExtId { get; set; }
}

public partial class tb_StatusJournal
{
    public int Id { get; set; }
    public int SourceId { get; set; }
    public int StatusTypeId { get; set; }
    public int StatusId { get; set; }
    public int UserId { get; set; }
    public System.DateTime DateTime { get; set; }
    public string Description { get; set; }
}

public partial class tb_Users
{
    public tb_Users()
    {
        this.tb_UsersRoles = new HashSet<tb_UsersRoles>();
    }

    public int Id { get; set; }
    public string Description { get; set; }
    public string Login { get; set; }
    public string EMail { get; set; }
    public string Phone { get; set; }
    public string Password { get; set; }
    public string LastName { get; set; }
    public string FirstName { get; set; }
    public string SurName { get; set; }
    public int StatusId { get; set; }
    public System.DateTime StatusDateTime { get; set; }
    public int StatusUserId { get; set; }
    public string StatusComment { get; set; }
    public byte[] Avatar { get; set; }
    public int ClientId { get; set; }
    public string NickName { get; set; }
    public string RegistrationAddress { get; set; }
    public bool IsDirector { get; set; }
    public string WarrantyNumber { get; set; }
    public Nullable<System.DateTime> WarrantyDate { get; set; }
    public string PassportPrefix { get; set; }
    public string PassportNumber { get; set; }
    public string PassportIssueInfo { get; set; }
    public Nullable<System.DateTime> PassportIssueDate { get; set; }
    public string PassportIssueCode { get; set; }
    public string TokenKey { get; set; }

    public virtual tb_Clients tb_Clients { get; set; }
    public virtual ICollection<tb_UsersRoles> tb_UsersRoles { get; set; }
}

public partial class tb_UsersRoles
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public int RoleId { get; set; }

    public virtual tb_Users tb_Users { get; set; }
    public virtual ts_Roles ts_Roles { get; set; }
}

public partial class ts_AccountTypes
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
}

public partial class ts_ClientDocumentTypes
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
}

public partial class ts_ClientTypes
{
    public ts_ClientTypes()
    {
        this.tb_Clients = new HashSet<tb_Clients>();
        this.ts_Roles = new HashSet<ts_Roles>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }

    public virtual ICollection<tb_Clients> tb_Clients { get; set; }
    public virtual ICollection<ts_Roles> ts_Roles { get; set; }
}

public partial class ts_CurrencyTypes
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
}

public partial class ts_ExternalAccountTypes
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
}

public partial class ts_LocationTypes
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
}

public partial class ts_OperationSourceTypes
{
    public ts_OperationSourceTypes()
    {
        this.tb_Operations = new HashSet<tb_Operations>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }

    public virtual ICollection<tb_Operations> tb_Operations { get; set; }
}

public partial class ts_OperationTypes
{
    public ts_OperationTypes()
    {
        this.tb_Operations = new HashSet<tb_Operations>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }

    public virtual ICollection<tb_Operations> tb_Operations { get; set; }
}

public partial class ts_PaymentTypes
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
}

public partial class ts_PropertyCategories
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
}

public partial class ts_RightObjects
{
    public ts_RightObjects()
    {
        this.ts_Rights = new HashSet<ts_Rights>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }

    public virtual ICollection<ts_Rights> ts_Rights { get; set; }
}

public partial class ts_Rights
{
    public ts_Rights()
    {
        this.tb_RolesRights = new HashSet<tb_RolesRights>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public int RightObjectId { get; set; }
    public int RightTypeId { get; set; }

    public virtual ICollection<tb_RolesRights> tb_RolesRights { get; set; }
    public virtual ts_RightObjects ts_RightObjects { get; set; }
    public virtual ts_RightTypes ts_RightTypes { get; set; }
}

public partial class ts_RightTypes
{
    public ts_RightTypes()
    {
        this.ts_Rights = new HashSet<ts_Rights>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }

    public virtual ICollection<ts_Rights> ts_Rights { get; set; }
}

public partial class ts_Roles
{
    public ts_Roles()
    {
        this.tb_RolesRights = new HashSet<tb_RolesRights>();
        this.tb_UsersRoles = new HashSet<tb_UsersRoles>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public int ClientTypeId { get; set; }

    public virtual ICollection<tb_RolesRights> tb_RolesRights { get; set; }
    public virtual ICollection<tb_UsersRoles> tb_UsersRoles { get; set; }
    public virtual ts_ClientTypes ts_ClientTypes { get; set; }
}

public partial class ts_Statuses
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public int StatusTypeId { get; set; }
}

public partial class ts_StatusTypes
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
}
