//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class EBSEntities : DbContext
{
    public EBSEntities()
        : base("name=EBSEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<tb_Accounts> tb_Accounts { get; set; }
    public virtual DbSet<tb_Actions> tb_Actions { get; set; }
    public virtual DbSet<tb_BillAllowances> tb_BillAllowances { get; set; }
    public virtual DbSet<tb_BillProfits> tb_BillProfits { get; set; }
    public virtual DbSet<tb_Bills> tb_Bills { get; set; }
    public virtual DbSet<tb_Blogs> tb_Blogs { get; set; }
    public virtual DbSet<tb_BuyoutRequest> tb_BuyoutRequest { get; set; }
    public virtual DbSet<tb_ClientDocuments> tb_ClientDocuments { get; set; }
    public virtual DbSet<tb_Clients> tb_Clients { get; set; }
    public virtual DbSet<tb_Counters> tb_Counters { get; set; }
    public virtual DbSet<tb_EBS_KioskEmissions> tb_EBS_KioskEmissions { get; set; }
    public virtual DbSet<tb_EmissionAddPercent> tb_EmissionAddPercent { get; set; }
    public virtual DbSet<tb_EmissionDocs> tb_EmissionDocs { get; set; }
    public virtual DbSet<tb_Emissioners> tb_Emissioners { get; set; }
    public virtual DbSet<tb_EmissionRequest> tb_EmissionRequest { get; set; }
    public virtual DbSet<tb_Emissions> tb_Emissions { get; set; }
    public virtual DbSet<tb_EmissionYield> tb_EmissionYield { get; set; }
    public virtual DbSet<tb_Experts> tb_Experts { get; set; }
    public virtual DbSet<tb_ExternalAccounts> tb_ExternalAccounts { get; set; }
    public virtual DbSet<tb_Investors> tb_Investors { get; set; }
    public virtual DbSet<tb_Locations> tb_Locations { get; set; }
    public virtual DbSet<tb_News> tb_News { get; set; }
    public virtual DbSet<tb_Operations> tb_Operations { get; set; }
    public virtual DbSet<tb_Organizations> tb_Organizations { get; set; }
    public virtual DbSet<tb_PayIn> tb_PayIn { get; set; }
    public virtual DbSet<tb_Payments> tb_Payments { get; set; }
    public virtual DbSet<tb_ReferrerReward> tb_ReferrerReward { get; set; }
    public virtual DbSet<tb_Referrers> tb_Referrers { get; set; }
    public virtual DbSet<tb_RolesRights> tb_RolesRights { get; set; }
    public virtual DbSet<tb_Settings> tb_Settings { get; set; }
    public virtual DbSet<tb_Shifts> tb_Shifts { get; set; }
    public virtual DbSet<tb_StatusJournal> tb_StatusJournal { get; set; }
    public virtual DbSet<tb_Users> tb_Users { get; set; }
    public virtual DbSet<tb_UsersRoles> tb_UsersRoles { get; set; }
    public virtual DbSet<ts_AccountTypes> ts_AccountTypes { get; set; }
    public virtual DbSet<ts_ClientDocumentTypes> ts_ClientDocumentTypes { get; set; }
    public virtual DbSet<ts_ClientTypes> ts_ClientTypes { get; set; }
    public virtual DbSet<ts_CurrencyTypes> ts_CurrencyTypes { get; set; }
    public virtual DbSet<ts_ExternalAccountTypes> ts_ExternalAccountTypes { get; set; }
    public virtual DbSet<ts_LocationTypes> ts_LocationTypes { get; set; }
    public virtual DbSet<ts_OperationSourceTypes> ts_OperationSourceTypes { get; set; }
    public virtual DbSet<ts_OperationTypes> ts_OperationTypes { get; set; }
    public virtual DbSet<ts_PaymentTypes> ts_PaymentTypes { get; set; }
    public virtual DbSet<ts_PropertyCategories> ts_PropertyCategories { get; set; }
    public virtual DbSet<ts_RightObjects> ts_RightObjects { get; set; }
    public virtual DbSet<ts_Rights> ts_Rights { get; set; }
    public virtual DbSet<ts_RightTypes> ts_RightTypes { get; set; }
    public virtual DbSet<ts_Roles> ts_Roles { get; set; }
    public virtual DbSet<ts_Statuses> ts_Statuses { get; set; }
    public virtual DbSet<ts_StatusTypes> ts_StatusTypes { get; set; }
}
