user  nginx;
worker_processes  auto;

error_log  /dev/stderr notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

stream {
    log_format stream_routing '$remote_addr [$time_local] '
                              '$protocol $status $bytes_sent $bytes_received '
                              '$session_time "$upstream_addr"';

    access_log /dev/stdout stream_routing;
    access_log /var/log/nginx/stream-access.log stream_routing;

    include /etc/nginx/stream.d/*.conf;
}
