# ==============================================================================
# Mosquitto ACL Configuration for Device SN: a4b0000773c82116d210826
# ==============================================================================

# Permissions for main UI / master application
user main_app
topic readwrite srv/a4b0000773c82116d210826/#
topic readwrite dev/a4b0000773c82116d210826/#

# Permissions for auxiliary service (publish events only)
user extra_service
topic write dev/a4b0000773c82116d210826/evt