//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2300
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2300.
// 
namespace PaySystemproxy
{
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;


    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "RapidaInterfaceServiceSoap", Namespace = "http://tempuri.org/")]
    public class ProxyInterfaceService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        /// <remarks/>
        public ProxyInterfaceService(string _url)
        {
            this.Url = _url;
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DoRequest", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DoRequest(string Function, string PaymExtId, string PaymSubjTp, string Amount, string Params, int ConnectionTimeout, string Rek, string TotalSum)
        {
            object[] results = this.Invoke("DoRequest", new object[] {
                        Function,
                        PaymExtId,
                        PaymSubjTp,
                        Amount,
                        Params,
                        ConnectionTimeout,
                        Rek,
                        TotalSum});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginDoRequest(string Function, string PaymExtId, string PaymSubjTp, string Amount, string Params, int ConnectionTimeout, string Rek, string TotalSum, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("DoRequest", new object[] {
                        Function,
                        PaymExtId,
                        PaymSubjTp,
                        Amount,
                        Params,
                        ConnectionTimeout,
                        Rek,
                        TotalSum}, callback, asyncState);
        }

        /// <remarks/>
        public string EndDoRequest(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
